# @generated by spec/generator — DO NOT EDIT.
# Source: https://ag-ui.com/spec/draft/schema.json
# Regenerate: pnpm --filter @ag-ui/spec generate

"""
Generated models, alongside the handwritten ones. Non-public: nothing in
ag_ui imports or re-exports this package, and its shape follows the schema
rather than the handwritten API.
"""
