# @generated by spec/generator — DO NOT EDIT.
# Source: https://ag-ui.com/spec/draft/schema.json
# Regenerate: pnpm --filter @ag-ui/spec generate



from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, field_validator
from pydantic.alias_generators import to_camel


class GeneratedBaseModel(BaseModel):
    """
    The generated base model. Wire names are camelCase behind snake_case
    attributes; unknown fields are kept, not dropped, so a boundary that wants
    to warn about them can still see them and a re-serialising intermediary
    does not lose them; and serialization omits fields that were never given
    a value — the default is omission, so no model has to remember it, while
    an explicit null that IS the data (a JSON Patch add of null) survives.
    Explicit null is rejected wherever the schema has no null: required
    fields reject it through their type, and each model guards its optional
    fields, because on this wire null is not how absence is spelled.
    """

    model_config = ConfigDict(
        extra="allow",
        alias_generator=to_camel,
        # Wire names only: accepting the snake_case attribute name as input
        # would invent meaning for a key the wire never defined — an unknown
        # message_id must land in the extras, not populate messageId.
        validate_by_alias=True,
        validate_by_name=False,
        # No lax coercion: the schema's "false" is not False and its "42" is
        # not 42. (Strict ints also reject 1.0, where JSON Schema accepts a
        # zero-fraction float — the rarer, safer direction.)
        strict=True,
    )

    def model_dump(self, **kwargs: Any) -> Any:
        kwargs.setdefault("exclude_unset", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs: Any) -> str:
        kwargs.setdefault("exclude_unset", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class EventType(str, Enum):
    """The discriminator carried by every event."""

    TEXT_MESSAGE_START = "TEXT_MESSAGE_START"
    TEXT_MESSAGE_CONTENT = "TEXT_MESSAGE_CONTENT"
    TEXT_MESSAGE_END = "TEXT_MESSAGE_END"
    TEXT_MESSAGE_CHUNK = "TEXT_MESSAGE_CHUNK"
    TOOL_CALL_START = "TOOL_CALL_START"
    TOOL_CALL_ARGS = "TOOL_CALL_ARGS"
    TOOL_CALL_END = "TOOL_CALL_END"
    TOOL_CALL_CHUNK = "TOOL_CALL_CHUNK"
    TOOL_CALL_RESULT = "TOOL_CALL_RESULT"
    STATE_SNAPSHOT = "STATE_SNAPSHOT"
    STATE_DELTA = "STATE_DELTA"
    MESSAGES_SNAPSHOT = "MESSAGES_SNAPSHOT"
    ACTIVITY_SNAPSHOT = "ACTIVITY_SNAPSHOT"
    ACTIVITY_DELTA = "ACTIVITY_DELTA"
    RAW = "RAW"
    CUSTOM = "CUSTOM"
    RUN_STARTED = "RUN_STARTED"
    RUN_FINISHED = "RUN_FINISHED"
    RUN_ERROR = "RUN_ERROR"
    STEP_STARTED = "STEP_STARTED"
    STEP_FINISHED = "STEP_FINISHED"
    REASONING_START = "REASONING_START"
    REASONING_MESSAGE_START = "REASONING_MESSAGE_START"
    REASONING_MESSAGE_CONTENT = "REASONING_MESSAGE_CONTENT"
    REASONING_MESSAGE_END = "REASONING_MESSAGE_END"
    REASONING_MESSAGE_CHUNK = "REASONING_MESSAGE_CHUNK"
    REASONING_END = "REASONING_END"
    REASONING_ENCRYPTED_VALUE = "REASONING_ENCRYPTED_VALUE"
    SUBAGENT_STARTED = "SUBAGENT_STARTED"
    SUBAGENT_FINISHED = "SUBAGENT_FINISHED"
    SUBAGENT_ERROR = "SUBAGENT_ERROR"


Metadata = Dict[str, Any]
"""
Extra information attached to an event, a message, a tool call, a tool, an
interrupt or a resume entry. Open by key: any JSON value is allowed under a
key, including null, because a null there is meaningful data. The object
itself may be absent but is never null when present. The key ag-ui is
reserved for the protocol's own use; reservation is by convention, since
validating the shape of a key's value would contradict being open by key.
"""


SubagentRunId = str
"""
An opaque handle for one subagent invocation, not a reusable name for a
subagent definition: two invocations of the same subagent carry two
different values. Named to mirror runId one level down, the way the
subagent's name mirrors agentId.
"""


TextMessageRole = Literal["developer", "system", "assistant", "user"]
"""
The roles a streamed text message may take. Excludes tool, which is carried
by TOOL_CALL_RESULT rather than streamed as text.
"""


class TextMessageStartEvent(GeneratedBaseModel):
    """
    Opens a streamed text message. The content arrives as
    TEXT_MESSAGE_CONTENT events and the message closes with
    TEXT_MESSAGE_END.
    """

    type: Literal[EventType.TEXT_MESSAGE_START]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """
    Identifies the message this stream builds, and ties the later content
    and end events to it.
    """
    role: Optional[TextMessageRole] = Field(default=None)
    """
    Who the message is from. An absent role means assistant; that meaning is
    normative and stated in the prose, because a validator treats a default
    as documentation rather than as behaviour.
    """
    name: Optional[str] = Field(default=None)
    """
    An optional display name for the author, for providers that distinguish
    several participants in one role.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", "role", "name", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class TextMessageContentEvent(GeneratedBaseModel):
    """Appends a fragment to a streamed text message."""

    type: Literal[EventType.TEXT_MESSAGE_CONTENT]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The message this fragment belongs to."""
    delta: str
    """
    The fragment to append. May be the empty string: providers emit empty
    deltas as keep-alives and while a tool call is being decided, and
    rejecting them would kill runs that are working correctly.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class TextMessageEndEvent(GeneratedBaseModel):
    """Closes a streamed text message."""

    type: Literal[EventType.TEXT_MESSAGE_END]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The message being closed."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class TextMessageChunkEvent(GeneratedBaseModel):
    """
    A shorthand that stands in for a start, content and end sequence, for
    producers that cannot know in advance where a message begins. Every
    field is optional because a continuation chunk omits what has not
    changed; which message a field-less chunk continues is a sequence
    question the prose specification answers.
    """

    type: Literal[EventType.TEXT_MESSAGE_CHUNK]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: Optional[str] = Field(default=None)
    """
    The message this chunk belongs to. Absent continues the message already
    open.
    """
    role: Optional[TextMessageRole] = Field(default=None)
    """Who the message is from, on the chunk that opens it."""
    delta: Optional[str] = Field(default=None)
    """The fragment to append. May be the empty string."""
    name: Optional[str] = Field(default=None)
    """An optional display name for the author."""

    @field_validator("timestamp", "metadata", "subagent_run_id", "message_id", "role", "delta", "name", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ToolCallStartEvent(GeneratedBaseModel):
    """
    Opens a tool call. The arguments arrive as TOOL_CALL_ARGS events and the
    call closes with TOOL_CALL_END.
    """

    type: Literal[EventType.TOOL_CALL_START]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    tool_call_id: str
    """
    Identifies the call, and ties the later args, end and result events to
    it.
    """
    tool_call_name: str
    """Which tool is being called."""
    parent_message_id: Optional[str] = Field(default=None)
    """
    The assistant message that holds this call. Absent means the producer
    did not attribute it to one.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", "parent_message_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ToolCallArgsEvent(GeneratedBaseModel):
    """Appends a fragment of a tool call's arguments."""

    type: Literal[EventType.TOOL_CALL_ARGS]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    tool_call_id: str
    """The call these arguments belong to."""
    delta: str
    """
    A fragment of the arguments, which concatenate into a JSON document.
    Deliberately a string rather than parsed JSON: a fragment of JSON is not
    itself JSON. May be the empty string.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ToolCallEndEvent(GeneratedBaseModel):
    """Closes a tool call, meaning its arguments are complete."""

    type: Literal[EventType.TOOL_CALL_END]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    tool_call_id: str
    """The call being closed."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ToolCallChunkEvent(GeneratedBaseModel):
    """
    A shorthand that stands in for a tool call's start, args and end
    sequence. Every field is optional for the same reason as
    TEXT_MESSAGE_CHUNK.
    """

    type: Literal[EventType.TOOL_CALL_CHUNK]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    tool_call_id: Optional[str] = Field(default=None)
    """The call this chunk belongs to. Absent continues the call already open."""
    tool_call_name: Optional[str] = Field(default=None)
    """Which tool is being called, on the chunk that opens it."""
    parent_message_id: Optional[str] = Field(default=None)
    """The assistant message that holds this call."""
    delta: Optional[str] = Field(default=None)
    """A fragment of the arguments. May be the empty string."""

    @field_validator("timestamp", "metadata", "subagent_run_id", "tool_call_id", "tool_call_name", "parent_message_id", "delta", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ToolCallResultEvent(GeneratedBaseModel):
    """
    Carries what a tool returned. Mints a tool message rather than appending
    to an existing one, which is why it has its own messageId.
    """

    type: Literal[EventType.TOOL_CALL_RESULT]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The tool message this result becomes."""
    tool_call_id: str
    """The call being answered."""
    content: str
    """
    What the tool returned, as a string. A tool returning structured data
    serialises it.
    """
    role: Optional[Literal["tool"]] = Field(default=None)
    """
    Present only for symmetry with the message it mints; the value is fixed,
    so a producer may leave it out.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", "role", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


State = Any
"""
Agent state. Any JSON value: the protocol carries state without interpreting
it, so an object, an array, a string and a number are all valid.
"""


class StateSnapshotEvent(GeneratedBaseModel):
    """
    Replaces the agent state wholesale. Sent when a delta cannot express the
    change, or to resynchronise a consumer.
    """

    type: Literal[EventType.STATE_SNAPSHOT]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    snapshot: State
    """The complete new state."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


JsonPointer = Annotated[str, Field(pattern=r"^(/([^/~]|~[01])*)*$")]
"""
A JSON Pointer as defined by RFC 6901. Either the empty string, meaning the
whole document, or a sequence of slash-prefixed reference tokens in which a
tilde is escaped as ~0 and a slash as ~1. A value with no leading slash, or
a tilde followed by anything other than 0 or 1, is not a JSON Pointer.
"""


class AddOperation(GeneratedBaseModel):
    """Inserts value at path. RFC 6902 section 4.1."""

    op: Literal["add"]
    """Discriminator for the add operation."""
    path: JsonPointer
    """Where to insert the value."""
    value: Any
    """
    The value to insert. Any JSON value, including null, which is a
    legitimate thing to add.
    """


class RemoveOperation(GeneratedBaseModel):
    """Removes the value at path. RFC 6902 section 4.2."""

    op: Literal["remove"]
    """Discriminator for the remove operation."""
    path: JsonPointer
    """What to remove."""


class ReplaceOperation(GeneratedBaseModel):
    """Replaces the value at path. RFC 6902 section 4.3."""

    op: Literal["replace"]
    """Discriminator for the replace operation."""
    path: JsonPointer
    """What to replace."""
    value: Any
    """The replacement. Any JSON value, including null."""


class MoveOperation(GeneratedBaseModel):
    """Moves the value at from to path. RFC 6902 section 4.4."""

    op: Literal["move"]
    """Discriminator for the move operation."""
    from_: JsonPointer = Field(alias="from")
    """Where the value is moved from."""
    path: JsonPointer
    """Where the value is moved to."""


class CopyOperation(GeneratedBaseModel):
    """Copies the value at from to path. RFC 6902 section 4.5."""

    op: Literal["copy"]
    """Discriminator for the copy operation."""
    from_: JsonPointer = Field(alias="from")
    """Where the value is copied from."""
    path: JsonPointer
    """Where the value is copied to."""


class TestOperation(GeneratedBaseModel):
    """Asserts that the value at path equals value. RFC 6902 section 4.6."""

    op: Literal["test"]
    """Discriminator for the test operation."""
    path: JsonPointer
    """What to compare."""
    value: Any
    """The value the target must equal. Any JSON value, including null."""


JsonPatchOperation = Annotated[
    Union[AddOperation, RemoveOperation, ReplaceOperation, MoveOperation, CopyOperation, TestOperation],
    Field(discriminator="op"),
]
"""
A single RFC 6902 operation. Exactly one of the operation shapes must match,
discriminated by op. Unlike the protocol's own objects, the operations are
open: RFC 6902 section 4 requires members an operation does not define to be
ignored rather than rejected, so a remove carrying a leftover value is a
valid patch. Two of the RFC's rules are relations between values rather than
shapes, so no static schema can express them and neither is checked here: a
move whose from is a proper prefix of its path (section 4.4), and any
operation whose pointer does not resolve in the target document. Both are
the applier's to reject.
"""


JsonPatch = List[JsonPatchOperation]
"""
A JSON Patch document as defined by RFC 6902, referenced by
STATE_DELTA.delta and ACTIVITY_DELTA.patch: an ordered sequence of
operations applied to a target document. An empty array is a valid no-op
patch. Whether the operations actually apply to the document they target is
a runtime question RFC 6902 leaves to the applier; structural validity here
says nothing about it.
"""


class StateDeltaEvent(GeneratedBaseModel):
    """Changes the agent state incrementally."""

    type: Literal[EventType.STATE_DELTA]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    delta: JsonPatch
    """
    The change, as an RFC 6902 patch against the current state. Structural
    validity here does not mean the patch applies: a well-formed operation
    may point at a path that does not exist, which RFC 6902 leaves to the
    applier.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class DeveloperMessage(GeneratedBaseModel):
    """Instructions from the application developer."""

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message within the conversation."""
    role: Literal["developer"]
    """
    Who the message is from. Each message definition narrows this to a
    single value.
    """
    name: Optional[str] = Field(default=None)
    """An optional display name for the author."""
    encrypted_value: Optional[str] = Field(default=None)
    """
    A provider's opaque artefact belonging to this message, stored by a
    consumer and returned on a later turn.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""
    content: str
    """
    The instructions. Required: a developer message with nothing in it says
    nothing.
    """

    @field_validator("subagent_run_id", "name", "encrypted_value", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class SystemMessage(GeneratedBaseModel):
    """Instructions from the system."""

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message within the conversation."""
    role: Literal["system"]
    """
    Who the message is from. Each message definition narrows this to a
    single value.
    """
    name: Optional[str] = Field(default=None)
    """An optional display name for the author."""
    encrypted_value: Optional[str] = Field(default=None)
    """
    A provider's opaque artefact belonging to this message, stored by a
    consumer and returned on a later turn.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""
    content: str
    """The instructions. Required."""

    @field_validator("subagent_run_id", "name", "encrypted_value", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class FunctionCall(GeneratedBaseModel):
    """The name and arguments of a tool call."""

    name: str
    """Which tool is being called."""
    arguments: str
    """
    The arguments as a JSON string, not as parsed JSON. Kept as written
    because a model can emit arguments that are not valid JSON, and losing
    them at the protocol boundary would hide the fault from the consumer
    that has to handle it.
    """


class ToolCall(GeneratedBaseModel):
    """
    A call an assistant message made. Carries no subagent attribution of its
    own and inherits its containing message's, since several calls can share
    one parent.
    """

    id: str
    """
    Identifies the call. The answering tool message carries this as its
    toolCallId.
    """
    type: Literal["function"]
    """The only kind of call the protocol models."""
    function: FunctionCall
    """What is being called, and with what."""
    encrypted_value: Optional[str] = Field(default=None)
    """A provider's opaque artefact belonging to this call."""
    metadata: Optional[Metadata] = Field(default=None)
    """
    Extra information attached to this call. Carried here rather than folded
    into the containing message, because several calls can share one parent
    and merging them would make the result depend on their order.
    """

    @field_validator("encrypted_value", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class AssistantMessage(GeneratedBaseModel):
    """
    A message from the agent. Content is optional because a turn may consist
    only of tool calls.
    """

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message within the conversation."""
    role: Literal["assistant"]
    """
    Who the message is from. Each message definition narrows this to a
    single value.
    """
    name: Optional[str] = Field(default=None)
    """An optional display name for the author."""
    encrypted_value: Optional[str] = Field(default=None)
    """
    A provider's opaque artefact belonging to this message, stored by a
    consumer and returned on a later turn.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""
    content: Optional[str] = Field(default=None)
    """What the agent said, if it said anything."""
    tool_calls: Optional[List[ToolCall]] = Field(default=None)
    """The tool calls this turn made."""

    @field_validator("subagent_run_id", "name", "encrypted_value", "metadata", "content", "tool_calls", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class TextInputContent(GeneratedBaseModel):
    """A text part."""

    type: Literal["text"]
    """Discriminator."""
    text: str
    """The text."""


class InputContentDataSource(GeneratedBaseModel):
    """Bytes carried inline."""

    type: Literal["data"]
    """Discriminator."""
    value: str
    """
    The bytes, base64-encoded. contentEncoding is an annotation rather than
    a constraint in 2020-12, so a malformed string still validates here;
    rejecting one is the decoder's job.
    """
    mime_type: str
    """
    What the bytes are. Required here, unlike on a URL source, because
    nothing else can tell a consumer how to read them.
    """


class InputContentUrlSource(GeneratedBaseModel):
    """Bytes referenced by URL, fetched by whoever needs them."""

    type: Literal["url"]
    """Discriminator."""
    value: str
    """
    The URL. Deliberately not constrained to a URI format, so a scheme a
    producer already uses is not rejected here.
    """
    mime_type: Optional[str] = Field(default=None)
    """
    What the resource is, when the producer knows. Optional, because the
    response can say.
    """

    @field_validator("mime_type", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


InputContentSource = Annotated[
    Union[InputContentDataSource, InputContentUrlSource],
    Field(discriminator="type"),
]
"""Where a media part's bytes come from: carried inline, or referenced by URL."""


class ImageInputContent(GeneratedBaseModel):
    """An image part."""

    type: Literal["image"]
    """Discriminator."""
    source: InputContentSource
    """Where the image comes from."""
    metadata: Optional[Any] = Field(default=None)
    """
    Extra information about this part. Unconstrained rather than an object:
    inherited from the SDKs, which declare it unknown rather than a record;
    listed under known divergences in the README rather than resolved here.
    """


class AudioInputContent(GeneratedBaseModel):
    """An audio part."""

    type: Literal["audio"]
    """Discriminator."""
    source: InputContentSource
    """Where the audio comes from."""
    metadata: Optional[Any] = Field(default=None)
    """
    Extra information about this part. Unconstrained, as on the other media
    parts.
    """


class VideoInputContent(GeneratedBaseModel):
    """A video part."""

    type: Literal["video"]
    """Discriminator."""
    source: InputContentSource
    """Where the video comes from."""
    metadata: Optional[Any] = Field(default=None)
    """
    Extra information about this part. Unconstrained, as on the other media
    parts.
    """


class DocumentInputContent(GeneratedBaseModel):
    """A document part."""

    type: Literal["document"]
    """Discriminator."""
    source: InputContentSource
    """Where the document comes from."""
    metadata: Optional[Any] = Field(default=None)
    """
    Extra information about this part. Unconstrained, as on the other media
    parts.
    """


InputContent = Annotated[
    Union[TextInputContent, ImageInputContent, AudioInputContent, VideoInputContent, DocumentInputContent],
    Field(discriminator="type"),
]
"""One part of a multimodal user message. Discriminated by type."""


class UserMessage(GeneratedBaseModel):
    """A message from the person using the application."""

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message within the conversation."""
    role: Literal["user"]
    """
    Who the message is from. Each message definition narrows this to a
    single value.
    """
    name: Optional[str] = Field(default=None)
    """An optional display name for the author."""
    encrypted_value: Optional[str] = Field(default=None)
    """
    A provider's opaque artefact belonging to this message, stored by a
    consumer and returned on a later turn.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""
    content: Union[str, List[InputContent]]
    """
    What the person sent: either plain text, or an ordered list of parts for
    a multimodal message.
    """

    @field_validator("subagent_run_id", "name", "encrypted_value", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ToolMessage(GeneratedBaseModel):
    """
    What a tool returned, as a message in the conversation. Stands alone
    rather than composing BaseMessage, because it carries no name.
    """

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message."""
    role: Literal["tool"]
    """
    Fixed. Declared here rather than inherited, because this message does
    not compose BaseMessage.
    """
    content: str
    """What the tool returned."""
    tool_call_id: str
    """The call this answers."""
    error: Optional[str] = Field(default=None)
    """
    Why the tool failed, when it did. Present alongside content rather than
    instead of it, so a partial result survives a failure.
    """
    encrypted_value: Optional[str] = Field(default=None)
    """A provider's opaque artefact belonging to this message."""
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""

    @field_validator("subagent_run_id", "error", "encrypted_value", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ActivityMessage(GeneratedBaseModel):
    """
    Structured progress that is not conversation content, materialised as a
    message so it keeps its place in the sequence. Stands alone rather than
    composing BaseMessage, because its content is an object rather than a
    string.
    """

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message."""
    role: Literal["activity"]
    """
    Fixed. Declared here rather than inherited, because this message does
    not compose BaseMessage.
    """
    activity_type: str
    """
    What kind of activity this is. An open string: the set is the
    producer's.
    """
    content: Dict[str, Any]
    """The activity's payload, open by key."""
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""

    @field_validator("subagent_run_id", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningMessage(GeneratedBaseModel):
    """
    A span of the agent's reasoning, materialised as a message. Stands alone
    rather than composing BaseMessage, because it carries no name.
    """

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the message."""
    role: Literal["reasoning"]
    """
    Fixed. Declared here rather than inherited, because this message does
    not compose BaseMessage.
    """
    content: str
    """The reasoning text."""
    encrypted_value: Optional[str] = Field(default=None)
    """A provider's opaque reasoning artefact belonging to this message."""
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this message."""

    @field_validator("subagent_run_id", "encrypted_value", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


Message = Annotated[
    Union[DeveloperMessage, SystemMessage, AssistantMessage, UserMessage, ToolMessage, ActivityMessage, ReasoningMessage],
    Field(discriminator="role"),
]
"""Any message in a conversation. Discriminated by role."""


class MessagesSnapshotEvent(GeneratedBaseModel):
    """
    The complete set of messages the producer owns, in order.
    Conversation-wide rather than a plain overwrite: a consumer may keep
    messages of its own that no producer tracks, so exactly how a snapshot
    reconciles with those is behavioural and belongs in the prose. Being
    conversation-wide it cannot belong to a single subagent, so it carries
    no attribution; it does establish which subagent owns each message it
    contains, through the messages themselves.
    """

    type: Literal[EventType.MESSAGES_SNAPSHOT]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    messages: List[Message]
    """The messages the producer is declaring, in order."""

    @field_validator("timestamp", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ActivitySnapshotEvent(GeneratedBaseModel):
    """
    Reports structured progress that is not conversation content, such as a
    step a UI renders as its own widget.
    """

    type: Literal[EventType.ACTIVITY_SNAPSHOT]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The activity message this describes."""
    activity_type: str
    """
    What kind of activity this is. An open string: the set is the
    producer's, not the protocol's.
    """
    content: Dict[str, Any]
    """The activity's payload, open by key."""
    replace: Optional[bool] = Field(default=None)
    """
    Whether this snapshot overwrites the activity's existing content. Absent
    means it does, and that meaning is normative; only an explicit false
    asks a consumer to leave what is already there. It does not ask for a
    merge — ACTIVITY_DELTA is how content is changed incrementally. What a
    consumer does with a non-overwriting snapshot is behavioural and belongs
    in the prose.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", "replace", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ActivityDeltaEvent(GeneratedBaseModel):
    """Changes an activity message's content incrementally."""

    type: Literal[EventType.ACTIVITY_DELTA]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The activity message being changed."""
    activity_type: str
    """What kind of activity this is."""
    patch: JsonPatch
    """The change, as an RFC 6902 patch against the activity's content."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RawEvent(GeneratedBaseModel):
    """
    Passes a provider-native event through untranslated, for consumers that
    need detail the protocol does not model.
    """

    type: Literal[EventType.RAW]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    event: Any
    """
    The provider's own event. Any JSON value, and required: an event whose
    only purpose is to carry this would say nothing without it.
    """
    source: Optional[str] = Field(default=None)
    """Which provider or framework the event came from."""

    @field_validator("timestamp", "metadata", "subagent_run_id", "source", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class CustomEvent(GeneratedBaseModel):
    """
    The protocol's extension point for an application's own events. Anything
    a consumer does with one is outside the protocol.
    """

    type: Literal[EventType.CUSTOM]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    name: str
    """
    What this custom event is. Required: without it a consumer cannot route
    the value.
    """
    value: Any
    """The payload. Any JSON value, and required."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class Tool(GeneratedBaseModel):
    """A tool the agent may call."""

    name: str
    """The tool's name, as the agent will call it."""
    description: str
    """What the tool does, for the agent to decide when to use it."""
    parameters: Optional[Any] = Field(default=None)
    """
    A JSON Schema describing the tool's arguments. Carried opaquely: the
    protocol does not constrain or validate it. Optional, because all three
    SDKs already treat it that way and a tool that takes no arguments has
    nothing to declare; an absent schema and an empty one mean the same
    thing to an agent.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """
    Extra information about the tool, for consumers that attach their own
    rendering or routing information to it.
    """

    @field_validator("metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class Context(GeneratedBaseModel):
    """
    A named piece of ambient information given to the agent for the run,
    distinct from the conversation.
    """

    description: str
    """What this context is, for the agent to interpret."""
    value: str
    """The context itself."""


class ResumeEntry(GeneratedBaseModel):
    """An answer to one interrupt, sent on the run that continues from it."""

    interrupt_id: str
    """The interrupt being answered."""
    status: Literal["resolved", "cancelled"]
    """Whether the interrupt was answered or abandoned."""
    payload: Optional[Any] = Field(default=None)
    """The answer the agent asked for and will act on. Any JSON value."""
    metadata: Optional[Metadata] = Field(default=None)
    """
    Envelope information about the response, such as signatures or routing
    keys, as opposed to payload, which is the answer itself.
    """

    @field_validator("metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RunAgentInput(GeneratedBaseModel):
    """
    A request to run an agent. Also echoed back as RUN_STARTED.input. Only
    threadId, runId and messages are required: those are the three the SDKs
    already agree on, and for tools and context an absent key and an empty
    array mean the same thing, so requiring them would catch nothing a
    producer could get wrong.
    """

    thread_id: str
    """The conversation this run belongs to."""
    run_id: str
    """Identifies this run."""
    parent_run_id: Optional[str] = Field(default=None)
    """The run that spawned this one."""
    state: Optional[State] = Field(default=None)
    """The state the run starts from."""
    messages: List[Message]
    """The conversation so far, in order."""
    tools: Optional[List[Tool]] = Field(default=None)
    """The tools the agent may call. Absent means none."""
    context: Optional[List[Context]] = Field(default=None)
    """Ambient information for the run. Absent means none."""
    forwarded_props: Optional[Any] = Field(default=None)
    """
    Application-specific values passed through to the agent untouched. Any
    JSON value.
    """
    resume: Optional[List[ResumeEntry]] = Field(default=None)
    """
    Answers to the interrupts that ended a previous run, when this run
    continues from one.
    """

    @field_validator("parent_run_id", "tools", "context", "resume", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RunStartedEvent(GeneratedBaseModel):
    """Opens a run. Run-scoped, so it carries no subagent attribution."""

    type: Literal[EventType.RUN_STARTED]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    thread_id: str
    """The conversation this run belongs to."""
    run_id: str
    """Identifies this run."""
    parent_run_id: Optional[str] = Field(default=None)
    """
    The run that spawned this one, when an agent invokes another agent as a
    separate run rather than as a subagent within one.
    """
    input: Optional[RunAgentInput] = Field(default=None)
    """
    The request this run was started from, echoed back so a consumer that
    did not make the request can still see what the agent was asked.
    """

    @field_validator("timestamp", "metadata", "parent_run_id", "input", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RunFinishedSuccessOutcome(GeneratedBaseModel):
    """
    The run completed. Equivalent to an absent outcome. Closed like every
    other object, which is also what keeps it from carrying the suspended
    sibling's interrupts — a success with an interrupt still pending would
    be a contradiction, not an extension.
    """

    type: Literal["success"]
    """Discriminator."""


class Interrupt(GeneratedBaseModel):
    """
    Something a run needs from outside before it can continue, such as an
    approval or a missing value.
    """

    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    id: str
    """Identifies the interrupt. A resume entry answers it by this id."""
    reason: str
    """
    Why the run stopped. An open string rather than an enumeration: the
    protocol does not attempt to classify every reason an agent might need
    input.
    """
    message: Optional[str] = Field(default=None)
    """A human-readable prompt for whoever answers."""
    tool_call_id: Optional[str] = Field(default=None)
    """The tool call this interrupt concerns, when it is a tool approval."""
    response_schema: Optional[Dict[str, Any]] = Field(default=None)
    """
    A JSON Schema describing the answer this interrupt expects, so a
    consumer can build a form for it. Carried opaquely: the protocol does
    not constrain or validate it. Restricted to an object because TypeScript
    and Python both declare it that way; .NET holds it as any JSON, and the
    ticket that commissioned this schema lists it among the arbitrary-JSON
    fields. Following the two that constrain it keeps the schema from
    accepting documents the reference client rejects, at the cost of
    rejecting the boolean schemas JSON Schema also permits — a bare true for
    "any answer". Recorded as a known divergence rather than settled.
    """
    expires_at: Optional[str] = Field(default=None)
    """
    When the interrupt stops being answerable. Deliberately unconstrained
    rather than a date-time format, because producers already disagree about
    the representation and tightening it here would reject streams that work
    today. The documented convention is ISO 8601, and a consumer comparing
    this value will parse it as a date, so a value that is not one leaves
    the interrupt looking permanently unexpired.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this interrupt."""

    @field_validator("subagent_run_id", "message", "tool_call_id", "response_schema", "expires_at", "metadata", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RunFinishedInterruptOutcome(GeneratedBaseModel):
    """
    The run is paused, waiting for something outside it. Resuming means
    starting a new run whose resume entries answer these interrupts.
    """

    type: Literal["interrupt"]
    """Discriminator."""
    interrupts: List[Interrupt] = Field(min_length=1)
    """
    What the run is waiting for. At least one: an interrupt outcome with
    nothing to answer would leave a consumer with nothing to do.
    """


RunFinishedOutcome = Annotated[
    Union[RunFinishedSuccessOutcome, RunFinishedInterruptOutcome],
    Field(discriminator="type"),
]
"""Why a run ended."""


class TokenUsage(GeneratedBaseModel):
    """
    Token counts for one provider and model. Every field is a label or a
    number — nothing content-bearing or identifying, no prompts,
    completions, messages, or thread, run and user identifiers.
    """

    provider: Optional[str] = Field(default=None)
    """Which provider served the request."""
    model: Optional[str] = Field(default=None)
    """Which model served the request."""
    input_tokens: Optional[int] = Field(default=None, ge=0, le=9007199254740991)
    """
    Prompt tokens consumed. Bounded like timestamp and for the same reason:
    a count above the JSON safe-integer range does not survive a round trip,
    so a consumer would silently read a different number than the producer
    wrote.
    """
    output_tokens: Optional[int] = Field(default=None, ge=0, le=9007199254740991)
    """Completion tokens produced."""
    total_tokens: Optional[int] = Field(default=None, ge=0, le=9007199254740991)
    """
    Total tokens, as the provider reports it rather than as a sum the
    protocol computes.
    """
    reasoning_tokens: Optional[int] = Field(default=None, ge=0, le=9007199254740991)
    """Tokens spent on reasoning, where the provider distinguishes them."""
    cached_input_tokens: Optional[int] = Field(default=None, ge=0, le=9007199254740991)
    """Prompt tokens served from a provider cache."""

    @field_validator("provider", "model", "input_tokens", "output_tokens", "total_tokens", "reasoning_tokens", "cached_input_tokens", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RunFinishedEvent(GeneratedBaseModel):
    """
    Closes a run that did not fail. Run-scoped, so it carries no subagent
    attribution.
    """

    type: Literal[EventType.RUN_FINISHED]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    thread_id: str
    """The conversation this run belongs to."""
    run_id: str
    """The run being closed."""
    result: Optional[Any] = Field(default=None)
    """The run's return value, if it has one. Any JSON value."""
    outcome: Optional[RunFinishedOutcome] = Field(default=None)
    """
    Why the run ended. Absent means success, so every producer written
    before outcomes existed is already conformant.
    """
    usage: Optional[List[TokenUsage]] = Field(default=None)
    """
    Token usage for the run, one entry per provider and model, so a run that
    invoked several models keeps them separate. A consumer that only wants
    totals sums across the entries.
    """

    @field_validator("timestamp", "metadata", "outcome", "usage", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class RunErrorEvent(GeneratedBaseModel):
    """
    Ends a run that failed. Run-scoped, so it carries no subagent
    attribution; a subagent that fails without ending the run reports
    SUBAGENT_ERROR instead.
    """

    type: Literal[EventType.RUN_ERROR]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    message: str
    """What went wrong, for a person to read."""
    code: Optional[str] = Field(default=None)
    """
    A machine-readable error code. An open string: the protocol defines no
    vocabulary.
    """
    usage: Optional[List[TokenUsage]] = Field(default=None)
    """
    Token usage accrued before the failure, for a run that completed one or
    more model calls before dying.
    """

    @field_validator("timestamp", "metadata", "code", "usage", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class StepStartedEvent(GeneratedBaseModel):
    """
    Opens a named step within a run, for producers whose frameworks have a
    step concept worth surfacing.
    """

    type: Literal[EventType.STEP_STARTED]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    step_name: str
    """
    The step's name. Identifies it: the matching STEP_FINISHED carries the
    same name.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class StepFinishedEvent(GeneratedBaseModel):
    """Closes a named step."""

    type: Literal[EventType.STEP_FINISHED]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    step_name: str
    """The step being closed."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningStartEvent(GeneratedBaseModel):
    """
    Opens a span of reasoning. A span may contain several reasoning
    messages.
    """

    type: Literal[EventType.REASONING_START]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The span being opened."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningMessageStartEvent(GeneratedBaseModel):
    """Opens a streamed reasoning message."""

    type: Literal[EventType.REASONING_MESSAGE_START]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The reasoning message this stream builds."""
    role: Literal["reasoning"]
    """
    Fixed, and required rather than defaulted. The requirement is inherited
    from the SDKs rather than chosen.
    """

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningMessageContentEvent(GeneratedBaseModel):
    """Appends a fragment to a streamed reasoning message."""

    type: Literal[EventType.REASONING_MESSAGE_CONTENT]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The reasoning message this fragment belongs to."""
    delta: str
    """The fragment to append. May be the empty string."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningMessageEndEvent(GeneratedBaseModel):
    """Closes a streamed reasoning message."""

    type: Literal[EventType.REASONING_MESSAGE_END]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The reasoning message being closed."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningMessageChunkEvent(GeneratedBaseModel):
    """
    A shorthand that stands in for a reasoning message's start, content and
    end sequence.
    """

    type: Literal[EventType.REASONING_MESSAGE_CHUNK]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: Optional[str] = Field(default=None)
    """
    The reasoning message this chunk belongs to. Absent continues the one
    already open.
    """
    delta: Optional[str] = Field(default=None)
    """The fragment to append. May be the empty string."""

    @field_validator("timestamp", "metadata", "subagent_run_id", "message_id", "delta", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class ReasoningEndEvent(GeneratedBaseModel):
    """Closes a span of reasoning."""

    type: Literal[EventType.REASONING_END]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    message_id: str
    """The span being closed."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


ReasoningEncryptedValueSubtype = Literal["tool-call", "message"]
"""Whether a REASONING_ENCRYPTED_VALUE belongs to a message or to a tool call."""


class ReasoningEncryptedValueEvent(GeneratedBaseModel):
    """
    Carries a provider's opaque, encrypted reasoning artefact, which a
    consumer stores and returns on a later turn without being able to read
    it.
    """

    type: Literal[EventType.REASONING_ENCRYPTED_VALUE]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation this belongs to. Absent means the parent agent
    produced it directly.
    """
    subtype: ReasoningEncryptedValueSubtype
    """
    What kind of thing entityId names, which decides where the value is
    stored.
    """
    entity_id: str
    """
    What the value belongs to: a message id or a tool call id, according to
    subtype.
    """
    encrypted_value: str
    """The provider's opaque artefact."""

    @field_validator("timestamp", "metadata", "subagent_run_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class SubagentStartedEvent(GeneratedBaseModel):
    """
    Announces that a subagent invocation has begun. Everything the subagent
    produces afterwards is attributed by carrying its subagentRunId, so a
    consumer can group the work without replaying the stream. Composed from
    BaseEvent alone rather than Attributable, because here subagentRunId
    identifies the subagent rather than attributing the event to one;
    attribution to an enclosing subagent is parentSubagentRunId.
    """

    type: Literal[EventType.SUBAGENT_STARTED]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: SubagentRunId
    """The invocation being announced."""
    name: str
    """
    The subagent's name, which is reusable across invocations, unlike
    subagentRunId.
    """
    description: Optional[str] = Field(default=None)
    """What this subagent is for, for a consumer to display."""
    parent_subagent_run_id: Optional[SubagentRunId] = Field(default=None)
    """
    The subagent invocation that spawned this one, for nested delegation.
    Absent means the parent agent spawned it directly.
    """
    parent_tool_call_id: Optional[str] = Field(default=None)
    """
    The tool call that spawned this subagent, for the pattern where agents
    are exposed to a model as tools. Lets a consumer tie the subagent to the
    call without reading rawEvent.
    """
    parent_message_id: Optional[str] = Field(default=None)
    """The message that held the spawning tool call."""

    @field_validator("timestamp", "metadata", "description", "parent_subagent_run_id", "parent_tool_call_id", "parent_message_id", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class SubagentFinishedSuccessOutcome(GeneratedBaseModel):
    """The subagent completed its work. Equivalent to an absent outcome."""

    type: Literal["success"]
    """Discriminator."""


class SubagentFinishedSuspendedOutcome(GeneratedBaseModel):
    """
    The subagent is paused awaiting outside input. Terminal for this stream,
    not for the subagent: a later run may continue the same invocation once
    the interrupts are answered.
    """

    type: Literal["suspended"]
    """Discriminator."""
    interrupt_ids: Optional[List[str]] = Field(default=None)
    """
    The run-level interrupts this subagent raised itself. May be empty or
    absent: a subagent suspended because a descendant interrupted owns no
    interrupt of its own. Each item: An Interrupt.id.
    """

    @field_validator("interrupt_ids", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


SubagentFinishedOutcome = Annotated[
    Union[SubagentFinishedSuccessOutcome, SubagentFinishedSuspendedOutcome],
    Field(discriminator="type"),
]
"""
Why a subagent's segment of a run ended. Mirrors RunFinishedOutcome one
level down.
"""


class SubagentFinishedEvent(GeneratedBaseModel):
    """
    Ends a subagent invocation's segment of this run, either because the
    work completed or because it is suspended awaiting outside input.
    """

    type: Literal[EventType.SUBAGENT_FINISHED]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: SubagentRunId
    """The invocation being closed."""
    result: Optional[Any] = Field(default=None)
    """
    The subagent's return value, if it has one. Any JSON value, mirroring
    RUN_FINISHED.result.
    """
    outcome: Optional[SubagentFinishedOutcome] = Field(default=None)
    """
    Why the segment ended. Absent means success. A suspended subagent is
    neither a success nor a failure, which is why saying so needs its own
    value rather than being inferred from a later interrupt.
    """

    @field_validator("timestamp", "metadata", "outcome", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


class SubagentErrorEvent(GeneratedBaseModel):
    """
    Reports that a subagent invocation failed. The run may continue: a
    parent agent is free to handle a failed subagent, which is why this is
    not RUN_ERROR.
    """

    type: Literal[EventType.SUBAGENT_ERROR]
    """
    Which event this is. Each event definition narrows this to a single
    value.
    """
    timestamp: Optional[int] = Field(default=None, ge=-9007199254740991, le=9007199254740991)
    """
    When the event was created. Bounded to the range JSON numbers survive a
    round trip in, so the value a consumer reads is the value the producer
    wrote. Deliberately not a float. The unit is not constrained here,
    because it never has been stated normatively; every SDK that sets it in
    practice uses milliseconds since the Unix epoch, and a producer choosing
    another unit will be misread by consumers even though it validates.
    Nothing in the protocol computes with this value.
    """
    raw_event: Optional[Any] = Field(default=None)
    """
    The provider-native event this one was translated from, carried verbatim
    for debugging and for consumers that need detail the protocol does not
    model. Any JSON value.
    """
    metadata: Optional[Metadata] = Field(default=None)
    """Extra information attached to this event."""
    subagent_run_id: SubagentRunId
    """The invocation that failed."""
    message: str
    """What went wrong, for a person to read."""
    code: Optional[str] = Field(default=None)
    """A machine-readable error code. An open string."""

    @field_validator("timestamp", "metadata", "code", mode="before")
    @classmethod
    def _reject_null(cls, value: Any) -> Any:
        if value is None:
            raise ValueError("null is not a value here; omit the field instead")
        return value


Event = Annotated[
    Union[TextMessageStartEvent, TextMessageContentEvent, TextMessageEndEvent, TextMessageChunkEvent, ToolCallStartEvent, ToolCallArgsEvent, ToolCallEndEvent, ToolCallChunkEvent, ToolCallResultEvent, StateSnapshotEvent, StateDeltaEvent, MessagesSnapshotEvent, ActivitySnapshotEvent, ActivityDeltaEvent, RawEvent, CustomEvent, RunStartedEvent, RunFinishedEvent, RunErrorEvent, StepStartedEvent, StepFinishedEvent, ReasoningStartEvent, ReasoningMessageStartEvent, ReasoningMessageContentEvent, ReasoningMessageEndEvent, ReasoningMessageChunkEvent, ReasoningEndEvent, ReasoningEncryptedValueEvent, SubagentStartedEvent, SubagentFinishedEvent, SubagentErrorEvent],
    Field(discriminator="type"),
]
"""
Any AG-UI event. Every member is normative: there is no optional tier and no
event a consumer may decline to implement. Discriminated by the type
property.
"""


Role = Literal["developer", "system", "assistant", "user", "tool", "activity", "reasoning"]
"""Every role a materialised message may have."""


