# @generated by spec/generator — DO NOT EDIT.
# Source: https://ag-ui.com/spec/draft/schema.json
# Regenerate: pnpm --filter @ag-ui/spec generate


PROTOCOL_VERSION = "draft"
"""
The protocol version this code was generated from: the version segment of
the schema's $id (https://ag-ui.com/spec/draft/schema.json). Never typed by
a human.
"""

