/**
 * The C# emitter: wire model in, the AGUI.Protobuf mappers out.
 *
 * Emits the .NET translation layer between the AGUI.Abstractions models and
 * the protoc-generated C# types (Grpc.Tools compiles those from the same
 * .proto files at build time). The event mapper is field-driven from the wire
 * model; the tables in this file are .NET idiom — which model class carries a
 * definition, which property name deviates from PascalCase, where a model
 * keeps a non-nullable string with an empty default — never field meaning.
 *
 * Two recorded gaps, mirrored from the other SDKs: the three subagent events
 * have no .NET models until #2350 (decode rejects them explicitly), and the
 * nested subagentRunId slots (Interrupt.8, Message.10) pass through unmapped
 * because those models have no property for them yet. Event-level
 * subagentRunId rides normally: BaseEvent carries the property.
 */

import type { Definition, Field, ObjectDefinition, TypeExpr } from "./ir";
import { buildScanGraph } from "./protobuf";
import type { WireModel } from "./protobuf";

/* ------------------------------------------------------------------ */
/* .NET idiom tables                                                    */
/* ------------------------------------------------------------------ */

/** Field -> .NET property, where PascalCase is not the property's name. */
const PROP_OVERRIDE: Record<string, string> = {
  "RunAgentInput.forwardedProps": "ForwardedProperties",
};

/**
 * Optional wire strings whose .NET model keeps a non-nullable string with an
 * empty default instead of a nullable property. Empty means absent on encode.
 */
const EMPTY_MEANS_ABSENT = new Set(["TextMessageStartEvent.role"]);

/**
 * Required arbitrary-JSON fields whose .NET model property is nullable
 * (JsonElement?) rather than a bare JsonElement.
 */
const NULLABLE_REQUIRED_ANY = new Set(["CustomEvent.value"]);

/** The events the .NET SDK has no model classes for yet (#2350). */
const NO_DOTNET_MODEL = new Set([
  "SubagentStartedEvent",
  "SubagentFinishedEvent",
  "SubagentErrorEvent",
]);

function pascalCase(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function propertyOf(definitionName: string, field: Field): string {
  return (
    PROP_OVERRIDE[`${definitionName}.${field.name}`] ?? pascalCase(field.name)
  );
}

function banner(schemaId: string): string {
  return [
    "// <auto-generated />",
    "// @generated by spec/generator — DO NOT EDIT.",
    `// Source: ${schemaId}`,
    "// Regenerate: pnpm --filter @ag-ui/spec generate",
    "#nullable enable",
  ].join("\n");
}

/* ------------------------------------------------------------------ */
/* Event mapper                                                        */
/* ------------------------------------------------------------------ */

type Kind =
  | "requiredString"
  | "optionalString"
  | "emptyMeansAbsentString"
  | "optionalInt"
  | "optionalBool"
  | "requiredAny"
  | "nullableRequiredAny"
  | "optionalAny"
  | "openMap"
  | "patchArray"
  | "messageArray"
  | "usageArray"
  | "interruptArray"
  | "stringArray"
  | "inputMessage"
  | "skip";

interface EventFieldPlan {
  field: Field;
  property: string;
  wireProperty: string;
  kind: Kind;
  /** Closed value set (literal / string enum), enforced on decode. */
  allowed?: string[];
}

function resolveAlias(defs: Map<string, Definition>, type: TypeExpr): TypeExpr {
  while (type.kind === "ref") {
    const target = defs.get(type.name);
    if (target?.kind !== "alias") return type;
    type = target.type;
  }
  return type;
}

/**
 * The closed value set of a literal or string-enum typed field. The wire
 * carries plain strings, so decode has to enforce the set itself — the
 * TypeScript validators reject out-of-set values and this runtime must too.
 */
function allowedValues(
  defs: Map<string, Definition>,
  field: Field,
): string[] | undefined {
  const resolved = resolveAlias(defs, field.type);
  if (resolved.kind === "literal") return [resolved.value];
  if (resolved.kind === "stringEnum") return resolved.values;
  if (resolved.kind === "ref") {
    const target = defs.get(resolved.name);
    if (target?.kind === "enum") return target.values;
  }
  return undefined;
}

function classify(
  defs: Map<string, Definition>,
  definitionName: string,
  field: Field,
): Kind {
  const key = `${definitionName}.${field.name}`;
  const resolved = resolveAlias(defs, field.type);
  switch (resolved.kind) {
    case "string":
    case "literal":
    case "stringEnum":
      if (EMPTY_MEANS_ABSENT.has(key)) return "emptyMeansAbsentString";
      return field.required ? "requiredString" : "optionalString";
    case "integer":
      return "optionalInt";
    case "boolean":
      return "optionalBool";
    case "any":
      if (!field.required) return "optionalAny";
      return NULLABLE_REQUIRED_ANY.has(key)
        ? "nullableRequiredAny"
        : "requiredAny";
    case "openMap":
      return "openMap";
    case "array": {
      const items =
        resolved.items.kind === "ref"
          ? defs.get(resolved.items.name)
          : undefined;
      if (items?.name === "JsonPatchOperation") return "patchArray";
      if (items?.name === "Message") return "messageArray";
      if (items?.name === "TokenUsage") return "usageArray";
      if (items?.name === "Interrupt") return "interruptArray";
      return "stringArray";
    }
    case "ref": {
      const target = defs.get(resolved.name);
      if (target?.kind === "enum") {
        // Enums ride the wire as strings.
        if (EMPTY_MEANS_ABSENT.has(key)) return "emptyMeansAbsentString";
        return field.required ? "requiredString" : "optionalString";
      }
      if (target?.name === "RunAgentInput") return "inputMessage";
      throw new Error(`no .NET mapping for ${key} -> ${resolved.name}`);
    }
    default:
      throw new Error(`no .NET mapping for ${key}`);
  }
}

function encodeField(
  plan: EventFieldPlan,
  proto: string,
  model: string,
): string[] {
  const p = `${proto}.${plan.wireProperty}`;
  const m = `${model}.${plan.property}`;
  switch (plan.kind) {
    case "requiredString":
      return [`${p} = ${m};`];
    case "optionalString":
      return [`if (${m} is not null)`, `{`, `    ${p} = ${m};`, `}`];
    case "emptyMeansAbsentString":
      return [`if (!string.IsNullOrEmpty(${m}))`, `{`, `    ${p} = ${m};`, `}`];
    case "optionalInt":
    case "optionalBool":
      return [`if (${m}.HasValue)`, `{`, `    ${p} = ${m}.Value;`, `}`];
    case "requiredAny":
      return [`${p} = ProtoValueConverter.ToValue(${m});`];
    case "nullableRequiredAny":
      // Required on the wire: a C#-null model value still writes a JSON null,
      // so a decoder that insists on the field's presence (the TypeScript
      // validators do) can read it.
      return [
        `${p} = ${m} is null`,
        `    ? new Google.Protobuf.WellKnownTypes.Value { NullValue = Google.Protobuf.WellKnownTypes.NullValue.NullValue }`,
        `    : ProtoValueConverter.ToValue(${m}.Value);`,
      ];
    case "optionalAny":
      return [
        `if (${m} is not null)`,
        `{`,
        `    ${p} = ProtoValueConverter.ToValue(${m}.Value);`,
        `}`,
      ];
    case "openMap":
      return [`${p} = ProtoValueConverter.ToStructOrNull(${m});`];
    case "patchArray":
      return [
        `if (${m}.ValueKind == JsonValueKind.Array)`,
        `{`,
        `    foreach (var operation in ${m}.EnumerateArray())`,
        `    {`,
        `        ${p}.Add(ProtoMessageMapper.ToProtoPatchOperation(operation));`,
        `    }`,
        `}`,
      ];
    case "messageArray":
      return [
        `foreach (var message in ${m})`,
        `{`,
        `    ${p}.Add(ProtoMessageMapper.ToProto(message));`,
        `}`,
      ];
    case "usageArray":
      return [`AddUsage(${p}, ${m});`];
    case "inputMessage":
      return [
        `if (${m} is not null)`,
        `{`,
        `    ${p} = ProtoMessageMapper.ToProtoRunAgentInput(${m});`,
        `}`,
      ];
    case "skip":
      return [];
    default:
      throw new Error(`encode: unhandled kind ${plan.kind}`);
  }
}

function decodeField(plan: EventFieldPlan, proto: string): string | undefined {
  const p = `${proto}.${plan.wireProperty}`;
  // Literal / string-enum fields reject out-of-set wire values, matching the
  // TypeScript validators.
  const guarded = (value: string): string =>
    plan.allowed
      ? `AssertOneOf(${value}, "${plan.field.name}", ${plan.allowed
          .map((entry) => JSON.stringify(entry))
          .join(", ")})`
      : value;
  switch (plan.kind) {
    case "requiredString":
      return `${plan.property} = ${guarded(p)},`;
    case "optionalString":
      return `${plan.property} = ${proto}.Has${plan.wireProperty} ? ${guarded(p)} : null,`;
    case "emptyMeansAbsentString":
      return `${plan.property} = ${proto}.Has${plan.wireProperty} ? ${guarded(p)} : string.Empty,`;
    case "optionalInt":
    case "optionalBool":
      return `${plan.property} = ${proto}.Has${plan.wireProperty} ? ${p} : null,`;
    case "requiredAny":
    case "nullableRequiredAny":
      // Required on the wire: an absent Value message is malformed (an
      // explicit JSON null rides as a non-null Value with null_value set).
      return `${plan.property} = ${p} is null ? throw MissingRequiredField("${plan.field.name}") : ProtoValueConverter.ToJsonElement(${p}),`;
    case "optionalAny":
      return `${plan.property} = ProtoValueConverter.ToJsonElementOrNull(${p}),`;
    case "openMap":
      // A required record must be present on the wire, as on the JSON path.
      return plan.field.required
        ? `${plan.property} = ProtoValueConverter.StructToJsonElementOrNull(${p}) ?? throw MissingRequiredField("${plan.field.name}"),`
        : `${plan.property} = ProtoValueConverter.StructToJsonElementOrNull(${p}) ?? default,`;
    case "usageArray":
      return `${plan.property} = BuildUsage(${p}),`;
    case "inputMessage":
      return `${plan.property} = ${p} is null ? null : ProtoMessageMapper.FromProtoRunAgentInput(${p}),`;
    case "skip":
      return undefined;
    default:
      return undefined;
  }
}

export function emitDotnet(
  wire: WireModel,
): Array<{ name: string; content: string }> {
  const { defs, model } = wire;
  const objectDef = (name: string): ObjectDefinition => {
    const definition = defs.get(name);
    if (definition?.kind !== "object")
      throw new Error(`${name} is not an object`);
    return definition;
  };
  const eventUnion = defs.get("Event");
  if (eventUnion?.kind !== "union") throw new Error("Event union missing");
  const baseNames = new Set(wire.baseFieldNames);

  const eventMessage = wire.messages.find((entry) => entry.name === "Event");
  const envelopeTags = (eventMessage?.oneof?.entries ?? [])
    .map((entry) => entry.number)
    .sort((a, b) => a - b);

  interface EventPlan {
    definition: ObjectDefinition;
    /** The protoc-generated C# names: oneof property and message class. */
    oneofProperty: string;
    protoType: string;
    eventType: string;
    fields: EventFieldPlan[];
    supported: boolean;
  }

  const plans: EventPlan[] = wire.envelope.map((entry) => {
    const definition = objectDef(entry.definition);
    const typeField = definition.fields.find((field) => field.name === "type");
    if (typeField?.type.kind !== "literal") throw new Error("event type field");
    const oneofProperty = entry.entry.split("_").map(pascalCase).join("");
    const fields: EventFieldPlan[] = definition.fields
      .filter((field) => !baseNames.has(field.name))
      .flatMap((field) => {
        // The flattened outcome expands at the wire level; handled bespoke.
        if (
          field.type.kind === "ref" &&
          defs.get(field.type.name)?.kind === "union"
        ) {
          return [];
        }
        const kind = classify(defs, definition.name, field);
        if (kind === "skip") return [];
        return [
          {
            field,
            property: propertyOf(definition.name, field),
            wireProperty: pascalCase(field.name),
            kind,
            allowed: allowedValues(defs, field),
          },
        ];
      });
    return {
      definition,
      oneofProperty,
      protoType: definition.name,
      eventType: typeField.type.value,
      fields,
      supported: !NO_DOTNET_MODEL.has(definition.name),
    };
  });

  /* -------- outcome flattening specs (RunFinished; Subagent skipped) ---- */
  const runFinished = plans.find(
    (plan) => plan.definition.name === "RunFinishedEvent",
  );
  if (!runFinished) throw new Error("RunFinishedEvent missing");

  const encodeCases = plans
    .filter((plan) => plan.supported)
    .map((plan) => {
      const name = plan.definition.name;
      const assignments = plan.fields
        .flatMap((field) => encodeField(field, "proto", "e"))
        .map((line) => `                ${line}`)
        .join("\n");
      const outcome =
        name === "RunFinishedEvent"
          ? `
                if (e.Outcome is RunFinishedInterruptOutcome interruptOutcome)
                {
                    proto.Outcome = "interrupt";
                    foreach (var interrupt in interruptOutcome.Interrupts)
                    {
                        proto.Interrupts.Add(ProtoMessageMapper.ToProtoInterrupt(interrupt));
                    }
                }
                else if (e.Outcome is RunFinishedSuccessOutcome)
                {
                    proto.Outcome = "success";
                }
                else
                {
                    proto.Outcome = string.Empty;
                }
`
          : "";
      return `            case ${name} e:
            {
                var proto = new Proto.${name}
                {
                    BaseEvent = BuildBaseEvent(e, Proto.EventType.${plan.oneofProperty}),
                };
${assignments}
${outcome}                return new Proto.Event { ${plan.oneofProperty} = proto };
            }`;
    })
    .join("\n");

  const decodeCases = plans
    .map((plan) => {
      const name = plan.definition.name;
      if (!plan.supported) {
        return `            case Proto.Event.EventOneofCase.${plan.oneofProperty}:
                // The subagent models land with #2350; until then the wire
                // entry is recognised and explicitly unsupported — never
                // surfaced as some other event.
                throw new NotSupportedException(
                    "Event type '${plan.eventType}' is not supported by this SDK yet (subagent models land with #2350).");`;
      }
      const initializers = plan.fields
        .map((field) => decodeField(field, "e"))
        .filter((line): line is string => line !== undefined)
        .map((line) => `                    ${line}`)
        .join("\n");
      const arrays = plan.fields
        .filter(
          (field) =>
            field.kind === "messageArray" || field.kind === "patchArray",
        )
        .map((field) => field);
      const post = arrays
        .map((field) => {
          if (field.kind === "messageArray") {
            return `                foreach (var message in e.${field.wireProperty})
                {
                    result.${field.property}.Add(ProtoMessageMapper.FromProto(message));
                }`;
          }
          return `                result.${field.property} = BuildPatchArray(e.${field.wireProperty});`;
        })
        .join("\n");
      const outcome =
        name === "RunFinishedEvent"
          ? `                result.Outcome = BuildOutcome(e);\n`
          : "";
      return `            case Proto.Event.EventOneofCase.${plan.oneofProperty}:
            {
                var e = proto.${plan.oneofProperty};
                var result = new ${name}
                {
${initializers}
                };
${post}${post ? "\n" : ""}${outcome}                ApplyBaseEvent(result, e.BaseEvent, Proto.EventType.${plan.oneofProperty});
                return result;
            }`;
    })
    .join("\n");

  const eventMapper = `${banner(model.schemaId)}

using System;
using System.Collections.Generic;
using System.Text.Json;
using AGUI.Abstractions;
using Google.Protobuf.Collections;
using Proto = AGUI.ProtocolBuffers;

namespace AGUI.Protobuf;

// Maps AG-UI .NET events to and from the generated protobuf Event oneof,
// generated from the same wire model as the TypeScript translation so the two
// runtimes cannot drift. Reshaping rules (outcome flattening, patch op<->enum)
// match sdks/typescript/packages/proto/src/proto.ts.
internal static class ProtoEventMapper
{
    public static Proto.Event ToProto(BaseEvent evt)
    {
        switch (evt)
        {
${encodeCases}
            default:
                throw new NotSupportedException(
                    $"Event type '{evt.Type}' is not representable in the AG-UI protobuf wire format by this SDK.");
        }
    }

    public static BaseEvent FromProto(Proto.Event proto)
    {
        switch (proto.EventCase)
        {
${decodeCases}
            default:
                throw new NotSupportedException(
                    "The protobuf message does not contain a supported AG-UI event variant.");
        }
    }

    private static Proto.BaseEvent BuildBaseEvent(BaseEvent evt, Proto.EventType type)
    {
        var baseEvent = new Proto.BaseEvent { Type = type };

        if (evt.Timestamp.HasValue)
        {
            baseEvent.Timestamp = evt.Timestamp.Value;
        }

        if (evt.RawEvent is not null)
        {
            baseEvent.RawEvent = ProtoValueConverter.ToValue(evt.RawEvent.Value);
        }

        baseEvent.Metadata = ProtoValueConverter.ToStructOrNull(evt.Metadata);

        return baseEvent;
    }

    private static void ApplyBaseEvent(
        BaseEvent target,
        Proto.BaseEvent? baseEvent,
        Proto.EventType expected)
    {
        if (baseEvent is null)
        {
            throw new System.IO.InvalidDataException(
                "Invalid event: the envelope entry carries no base event.");
        }

        // The envelope entry is authoritative; a base event declaring a
        // different type (or an out-of-enum value) is a contradiction another
        // runtime could resolve differently, so it rejects.
        if (baseEvent.Type != expected)
        {
            throw new System.IO.InvalidDataException(
                $"Invalid event: the envelope carries {expected} but the base event says {baseEvent.Type}.");
        }

        if (baseEvent.HasTimestamp)
        {
            target.Timestamp = baseEvent.Timestamp;
        }

        if (baseEvent.RawEvent is not null)
        {
            target.RawEvent = ProtoValueConverter.ToJsonElement(baseEvent.RawEvent);
        }

        target.Metadata = ProtoValueConverter.StructToJsonElementOrNull(baseEvent.Metadata);
    }

    private static RunFinishedOutcome? BuildOutcome(Proto.RunFinishedEvent proto)
    {
        if (proto.Outcome == "interrupt")
        {
            // The schema requires at least one interrupt: an interrupt
            // outcome with nothing to answer would leave a consumer with
            // nothing to do, and the TypeScript validators reject it.
            if (proto.Interrupts.Count == 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: interrupt outcome carries no interrupts.");
            }

            var outcome = new RunFinishedInterruptOutcome();
            foreach (var interrupt in proto.Interrupts)
            {
                outcome.Interrupts.Add(ProtoMessageMapper.FromProtoInterrupt(interrupt));
            }

            return outcome;
        }

        if (proto.Outcome == "success")
        {
            // A success (or absent) outcome carrying interrupts is a
            // contradiction: a consumer branching on the discriminator would
            // finish the run with an interrupt still pending.
            if (proto.Interrupts.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: outcome success cannot carry interrupts.");
            }

            return new RunFinishedSuccessOutcome();
        }

        if (proto.Outcome.Length == 0)
        {
            if (proto.Interrupts.Count > 0)
            {
                throw new System.IO.InvalidDataException(
                    "Invalid event: absent outcome cannot carry interrupts.");
            }

            return null;
        }

        // An unknown discriminator must not silently decode to "no outcome",
        // which would imply success; the JSON path errors on it too.
        throw new System.IO.InvalidDataException(
            $"Invalid event: unknown outcome '{proto.Outcome}'.");
    }

    // Token usage maps 1:1 onto the repeated Usage field. An absent list and an
    // empty list both encode to zero entries, so legacy events (no usage) stay
    // byte-for-byte identical on the wire; decoding mirrors that by returning
    // null rather than an empty list.
    private static void AddUsage(RepeatedField<Proto.Usage> target, IList<TokenUsage>? usage)
    {
        if (usage is null)
        {
            return;
        }

        foreach (var entry in usage)
        {
            var proto = new Proto.Usage();
            if (entry.Provider is not null)
            {
                proto.Provider = entry.Provider;
            }

            if (entry.Model is not null)
            {
                proto.Model = entry.Model;
            }

            if (entry.InputTokens is { } inputTokens)
            {
                proto.InputTokens = inputTokens;
            }

            if (entry.OutputTokens is { } outputTokens)
            {
                proto.OutputTokens = outputTokens;
            }

            if (entry.TotalTokens is { } totalTokens)
            {
                proto.TotalTokens = totalTokens;
            }

            if (entry.ReasoningTokens is { } reasoningTokens)
            {
                proto.ReasoningTokens = reasoningTokens;
            }

            if (entry.CachedInputTokens is { } cachedInputTokens)
            {
                proto.CachedInputTokens = cachedInputTokens;
            }

            target.Add(proto);
        }
    }

    private static IList<TokenUsage>? BuildUsage(RepeatedField<Proto.Usage> usage)
    {
        if (usage.Count == 0)
        {
            return null;
        }

        var result = new List<TokenUsage>(usage.Count);
        foreach (var entry in usage)
        {
            result.Add(new TokenUsage
            {
                Provider = entry.HasProvider ? entry.Provider : null,
                Model = entry.HasModel ? entry.Model : null,
                InputTokens = entry.HasInputTokens ? entry.InputTokens : null,
                OutputTokens = entry.HasOutputTokens ? entry.OutputTokens : null,
                TotalTokens = entry.HasTotalTokens ? entry.TotalTokens : null,
                ReasoningTokens = entry.HasReasoningTokens ? entry.ReasoningTokens : null,
                CachedInputTokens = entry.HasCachedInputTokens ? entry.CachedInputTokens : null,
            });
        }

        return result;
    }

    internal static string AssertOneOf(string value, string field, params string[] allowed)
    {
        foreach (var entry in allowed)
        {
            if (value == entry)
            {
                return value;
            }
        }

        throw new System.IO.InvalidDataException(
            $"Invalid event: {field} carries unknown value '{value}'.");
    }

    internal static System.IO.InvalidDataException MissingRequiredField(string field)
        => new($"Invalid event: required field '{field}' is missing.");

    private static JsonElement BuildPatchArray(RepeatedField<Proto.JsonPatchOperation> operations)
    {
        return JsonElementFactory.Create(writer =>
        {
            writer.WriteStartArray();
            foreach (var operation in operations)
            {
                ProtoMessageMapper.WriteProtoPatchOperation(writer, operation);
            }

            writer.WriteEndArray();
        });
    }
}
`;

  /* ------------------------------------------------------------------ */
  /* Wire guards                                                          */
  /* ------------------------------------------------------------------ */

  // The malformed-wire scan, generated from the shared scan graph: canonical
  // protobuf parsers (this runtime's included) MERGE a repeated occurrence of
  // a singular message-typed field where ts-proto REPLACES it, and a oneof
  // carrying several distinct arms keeps only the last here while the
  // TypeScript translation sees them all. Either way the same bytes would
  // materialise differently across runtimes, so the scan rejects them first.
  // Closed sets for the bespoke message-mapper guards, read from the schema
  // so the values can never drift from it.
  const closedSet = (definitionName: string, fieldName: string): string => {
    const definition = objectDef(definitionName);
    const field = definition.fields.find((entry) => entry.name === fieldName);
    if (!field) throw new Error(`${definitionName}.${fieldName} missing`);
    const values = allowedValues(defs, field);
    if (!values)
      throw new Error(`${definitionName}.${fieldName} is not closed`);
    return values.map((value) => JSON.stringify(value)).join(", ");
  };

  const scanGraph = buildScanGraph(wire);

  const scanMethods = scanGraph.specs
    .map((spec) => {
      const armNumbers = spec.arms?.numbers ?? [];
      const nestedCases = spec.descend
        .map(
          (entry) =>
            `                            case ${entry.number}:
                                Scan${entry.child}(data.Slice(offset, (int)length));
                                break;`,
        )
        .join("\n");
      const singularCheck =
        spec.singular.length === 0
          ? ""
          : `
                        if (${spec.singular
                          .map((n) => `field == ${n}`)
                          .join(" || ")})
                        {
                            // A duplicate of a singular message-typed field
                            // merges here and replaces in ts-proto; reject.
                            ulong bit = 1UL << (int)field;
                            if ((seenSingular & bit) != 0)
                            {
                                throw new InvalidDataException(
                                    "Invalid event: duplicate singular field.");
                            }

                            seenSingular |= bit;
                        }
`;
      const armCheck =
        armNumbers.length === 0
          ? ""
          : `
                        if (${armNumbers
                          .map((n) => `field == ${n}`)
                          .join(" || ")})
                        {
                            if (seenArm != 0 && seenArm != field)
                            {
                                throw new InvalidDataException(
                                    "Invalid event: ${spec.arms?.name} carries more than one arm.");
                            }

                            seenArm = field;
                        }
`;
      const locals = [
        spec.singular.length > 0 ? "        ulong seenSingular = 0;\n" : "",
        armNumbers.length > 0 ? "        uint seenArm = 0;\n" : "",
      ].join("");
      return `    private static void Scan${spec.name}(ReadOnlySpan<byte> data)
    {
        int offset = 0;
        int groupDepth = 0;
${locals}
        while (offset < data.Length)
        {
            uint tag = ReadVarint(data, ref offset);
            uint field = tag / 8;
            uint wireType = tag % 8;

            if (field == 0)
            {
                throw new InvalidDataException("Invalid event: field zero is not a legal tag.");
            }

            if (wireType == 3)
            {
                groupDepth += 1;
                continue;
            }

            if (wireType == 4)
            {
                groupDepth -= 1;
                if (groupDepth < 0)
                {
                    throw new InvalidDataException("Invalid event: unbalanced group.");
                }

                continue;
            }

            switch (wireType)
            {
                case 0:
                    ReadVarint(data, ref offset);
                    break;
                case 1:
                    offset += 8;
                    break;
                case 2:
                {
                    uint length = ReadVarint(data, ref offset);
                    if (offset + (long)length > data.Length)
                    {
                        throw new InvalidDataException("Invalid event: truncated payload.");
                    }

                    if (groupDepth == 0)
                    {
${singularCheck}${armCheck}                        switch (field)
                        {
${nestedCases || "                            default:\n                                break;"}
                        }
                    }

                    offset += (int)length;
                    break;
                }
                case 5:
                    offset += 4;
                    break;
                default:
                    throw new InvalidDataException("Invalid event: unknown wire type.");
            }

            if (offset > data.Length)
            {
                throw new InvalidDataException("Invalid event: truncated payload.");
            }
        }

        if (groupDepth != 0)
        {
            throw new InvalidDataException("Invalid event: unbalanced group.");
        }
    }`;
    })
    .join("\n\n");

  const envelopeScanCases = scanGraph.envelope
    .map(
      (entry) =>
        `                        case ${entry.number}:
                            Scan${entry.child}(data.Slice(offset, (int)length));
                            break;`,
    )
    .join("\n");

  const wireGuards = `${banner(model.schemaId)}

using System;
using System.IO;

namespace AGUI.Protobuf;

// The envelope pre-scan, generated from the same wire model as the
// TypeScript scan: a repeated KNOWN event tag decodes differently across
// runtimes (canonical protobuf merges, others overwrite), so neither silent
// behaviour is acceptable. Unknown field numbers are protobuf's to ignore,
// repeated or not, so forward compatibility is untouched. Field zero is not a
// legal tag. Legacy group fields nest and are skipped wholesale.
internal static class WireGuards
{
    private static readonly bool[] KnownEnvelopeTags = BuildKnownTags();

    private static bool[] BuildKnownTags()
    {
        var known = new bool[${Math.max(...envelopeTags) + 1}];
${envelopeTags.map((tag) => `        known[${tag}] = true;`).join("\n")}
        return known;
    }

    public static void AssertWellFormedEnvelope(ReadOnlySpan<byte> data)
    {
        int knownTags = 0;
        int offset = 0;
        int groupDepth = 0;

        while (offset < data.Length)
        {
            uint tag = ReadVarint(data, ref offset);
            uint field = tag / 8;
            uint wireType = tag % 8;

            if (field == 0)
            {
                throw new InvalidDataException("Invalid event: field zero is not a legal tag.");
            }

            if (wireType == 3)
            {
                groupDepth += 1;
                continue;
            }

            if (wireType == 4)
            {
                groupDepth -= 1;
                if (groupDepth < 0)
                {
                    throw new InvalidDataException("Invalid event: unbalanced group.");
                }

                continue;
            }

            if (groupDepth == 0 && field < (uint)KnownEnvelopeTags.Length && KnownEnvelopeTags[(int)field])
            {
                // Exactly one event per envelope: a second known tag — a
                // repeat or a different event — decodes differently across
                // runtimes (canonical protobuf merges or last-wins where
                // others overwrite), so it rejects.
                if (knownTags > 0)
                {
                    throw new InvalidDataException(
                        "Invalid event: the envelope carries more than one event.");
                }

                knownTags += 1;
            }

            switch (wireType)
            {
                case 0:
                    ReadVarint(data, ref offset);
                    break;
                case 1:
                    offset += 8;
                    break;
                case 2:
                {
                    // Two statements on purpose: adding the call inline would
                    // capture offset before the varint advances it.
                    uint length = ReadVarint(data, ref offset);
                    if (offset + (long)length > data.Length)
                    {
                        throw new InvalidDataException("Invalid event: truncated payload.");
                    }

                    if (groupDepth == 0)
                    {
                        // Events that can carry a nested oneof get their
                        // payload scanned for arm exclusivity too.
                        switch (field)
                        {
${envelopeScanCases}
                            default:
                                break;
                        }
                    }

                    offset += (int)length;
                    break;
                }
                case 5:
                    offset += 4;
                    break;
                default:
                    throw new InvalidDataException("Invalid event: unknown wire type.");
            }

            if (offset > data.Length)
            {
                throw new InvalidDataException("Invalid event: truncated payload.");
            }
        }

        if (groupDepth != 0)
        {
            throw new InvalidDataException("Invalid event: unbalanced group.");
        }
    }

    // The nested scans, one message level each, generated from the shared
    // scan graph. Two malformed shapes reject: a duplicate occurrence of a
    // singular message-typed field (canonical parsers merge, ts-proto
    // replaces) and a oneof carrying more than one distinct arm (this
    // runtime keeps the last, the TypeScript translation sees them all).
    // google.protobuf.* payloads are counted but not entered: their insides
    // belong to the runtime library, a recorded scan boundary.
${scanMethods}

    // Mirrors the uint32 reader truncation exactly: the fifth byte contributes
    // only its low four bits, later bytes none — otherwise an overlong tag
    // encoding would dodge duplicate detection while the real decoder still
    // reads the canonical field number.
    private static uint ReadVarint(ReadOnlySpan<byte> data, ref int offset)
    {
        uint result = 0;
        int shift = 0;
        while (true)
        {
            if (offset >= data.Length)
            {
                throw new InvalidDataException("Invalid event: truncated varint.");
            }

            byte value = data[offset++];
            if (shift < 28)
            {
                result += (uint)(value & 0x7f) << shift;
            }
            else if (shift == 28)
            {
                result += (uint)(value & 0x0f) << 28;
            }

            shift += 7;
            if ((value & 0x80) == 0)
            {
                return result;
            }
        }
    }
}
`;

  /* ------------------------------------------------------------------ */
  /* Message mapper                                                       */
  /* ------------------------------------------------------------------ */

  const messageUnion = defs.get("Message");
  if (messageUnion?.kind !== "union") throw new Error("Message union missing");

  const messageMapper = `${banner(model.schemaId)}

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using AGUI.Abstractions;
using Google.Protobuf.WellKnownTypes;
using Proto = AGUI.ProtocolBuffers;

namespace AGUI.Protobuf;

// Maps the AG-UI .NET message/content/tool-call/interrupt/json-patch/input
// model to and from the generated protobuf messages, generated from the same
// wire model as the TypeScript translation. Note: subagentRunId (wire slots
// Interrupt.8 and Message.10) has no .NET model property until #2350, so it
// passes through unmapped here, exactly as the other SDKs record.
internal static class ProtoMessageMapper
{
    public static Proto.Message ToProto(AGUIMessage message)
    {
        var proto = new Proto.Message
        {
            Id = message.Id ?? string.Empty,
            Role = message.Role,
            Metadata = ProtoValueConverter.ToStructOrNull(message.Metadata),
        };

        switch (message)
        {
            case AGUIUserMessage user:
                if (user.Name is not null)
                {
                    proto.Name = user.Name;
                }

                if (user.EncryptedValue is not null)
                {
                    proto.EncryptedValue = user.EncryptedValue;
                }

                if (user.Content.Value is IList<AGUIInputContent> parts)
                {
                    foreach (var part in parts)
                    {
                        var protoPart = ToProtoContentPart(part);
                        if (protoPart is not null)
                        {
                            proto.ContentParts.Add(protoPart);
                        }
                    }
                }
                else if (user.Content.Value is string text)
                {
                    proto.Content = text;
                }
                else
                {
                    proto.Content = string.Empty;
                }

                break;
            case AGUIAssistantMessage assistant:
                if (assistant.Content is not null)
                {
                    proto.Content = assistant.Content;
                }

                if (assistant.Name is not null)
                {
                    proto.Name = assistant.Name;
                }

                if (assistant.EncryptedValue is not null)
                {
                    proto.EncryptedValue = assistant.EncryptedValue;
                }

                if (assistant.ToolCalls is not null)
                {
                    foreach (var toolCall in assistant.ToolCalls)
                    {
                        proto.ToolCalls.Add(ToProtoToolCall(toolCall));
                    }
                }

                break;
            case AGUISystemMessage system:
                proto.Content = system.Content;
                if (system.Name is not null)
                {
                    proto.Name = system.Name;
                }

                if (system.EncryptedValue is not null)
                {
                    proto.EncryptedValue = system.EncryptedValue;
                }

                break;
            case AGUIDeveloperMessage developer:
                proto.Content = developer.Content;
                if (developer.Name is not null)
                {
                    proto.Name = developer.Name;
                }

                if (developer.EncryptedValue is not null)
                {
                    proto.EncryptedValue = developer.EncryptedValue;
                }

                break;
            case AGUIToolMessage tool:
                proto.Content = tool.Content;
                proto.ToolCallId = tool.ToolCallId;
                if (tool.Error is not null)
                {
                    proto.Error = tool.Error;
                }

                if (tool.EncryptedValue is not null)
                {
                    proto.EncryptedValue = tool.EncryptedValue;
                }

                break;
            case AGUIActivityMessage activity:
                proto.ActivityType = activity.ActivityType;
                proto.ActivityContent = ProtoValueConverter.ToStructOrNull(activity.Content);
                break;
            case AGUIReasoningMessage reasoning:
                proto.Content = reasoning.Content;
                if (reasoning.EncryptedValue is not null)
                {
                    proto.EncryptedValue = reasoning.EncryptedValue;
                }

                break;
            default:
                throw new NotSupportedException(
                    $"Message role '{message.Role}' is not supported by the AG-UI protobuf wire format.");
        }

        return proto;
    }

    public static AGUIMessage FromProto(Proto.Message proto)
    {
        AssertRoleExclusiveCarriers(proto);
        var message = FromProtoCore(proto);
        message.Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata);
        return message;
    }

    // Content carriers are role-exclusive; a message carrying a carrier its
    // role does not use would lose data whichever one decode preferred.
    private static void AssertRoleExclusiveCarriers(Proto.Message proto)
    {
        bool isActivity = proto.Role == AGUIRoles.Activity;
        bool isUser = proto.Role == AGUIRoles.User;

        if (proto.ActivityContent is not null && !isActivity)
        {
            throw new InvalidDataException(
                "Invalid event: message carries activity content for a non-activity role.");
        }

        if (isActivity && (proto.HasContent || proto.ContentParts.Count > 0))
        {
            throw new InvalidDataException(
                "Invalid event: activity content cannot ride with other content forms.");
        }

        if (!isUser && proto.ContentParts.Count > 0)
        {
            throw new InvalidDataException(
                "Invalid event: message carries content parts for a role that has none.");
        }

        if (isUser && proto.HasContent && proto.ContentParts.Count > 0)
        {
            throw new InvalidDataException(
                "Invalid event: message carries both string content and content parts.");
        }
    }

    private static AGUIMessage FromProtoCore(Proto.Message proto)
    {
        // An empty id is schema-valid and the wire cannot carry an absent one
        // (the field is required), so empty stays empty — as in TypeScript.
        var id = proto.Id;

        switch (proto.Role)
        {
            case AGUIRoles.User:
            {
                var user = new AGUIUserMessage
                {
                    Id = id,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };

                if (proto.HasContent)
                {
                    user.Content = proto.Content;
                }
                else
                {
                    // String content rides the content field; anything else is
                    // the parts array — including an empty one, which is valid
                    // content of its own. A part with no recognisable arm is
                    // rejected, not erased.
                    var parts = new List<AGUIInputContent>();
                    foreach (var protoPart in proto.ContentParts)
                    {
                        var part = FromProtoContentPart(protoPart);
                        if (part is null)
                        {
                            throw new InvalidDataException(
                                "Invalid event: unreadable content part.");
                        }

                        parts.Add(part);
                    }

                    user.Content = parts;
                }

                return user;
            }
            case AGUIRoles.Assistant:
            {
                var assistant = new AGUIAssistantMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : null,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };

                if (proto.ToolCalls.Count > 0)
                {
                    var toolCalls = new List<AGUIToolCall>();
                    foreach (var protoToolCall in proto.ToolCalls)
                    {
                        toolCalls.Add(FromProtoToolCall(protoToolCall));
                    }

                    assistant.ToolCalls = toolCalls;
                }

                return assistant;
            }
            case AGUIRoles.System:
                return new AGUISystemMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            case AGUIRoles.Developer:
                return new AGUIDeveloperMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    Name = proto.HasName ? proto.Name : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            case AGUIRoles.Tool:
                return new AGUIToolMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    ToolCallId = proto.HasToolCallId ? proto.ToolCallId : string.Empty,
                    Error = proto.HasError ? proto.Error : null,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            case AGUIRoles.Activity:
                return new AGUIActivityMessage
                {
                    Id = id,
                    ActivityType = proto.HasActivityType ? proto.ActivityType : string.Empty,
                    Content = ProtoValueConverter.StructToJsonElementOrNull(proto.ActivityContent)
                        ?? throw ProtoEventMapper.MissingRequiredField("content"),
                };
            case AGUIRoles.Reasoning:
                return new AGUIReasoningMessage
                {
                    Id = id,
                    Content = proto.HasContent ? proto.Content : string.Empty,
                    EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
                };
            default:
                throw new NotSupportedException(
                    $"Message role '{proto.Role}' is not supported by the AG-UI protobuf wire format.");
        }
    }

    public static Proto.RunAgentInput ToProtoRunAgentInput(RunAgentInput input)
    {
        var proto = new Proto.RunAgentInput
        {
            ThreadId = input.ThreadId,
            RunId = input.RunId,
        };

        if (input.ParentRunId is not null)
        {
            proto.ParentRunId = input.ParentRunId;
        }

        if (input.State is not null)
        {
            proto.State = ProtoValueConverter.ToValue(input.State.Value);
        }

        foreach (var message in input.Messages)
        {
            proto.Messages.Add(ToProto(message));
        }

        if (input.Tools is not null)
        {
            foreach (var tool in input.Tools)
            {
                proto.Tools.Add(ToProtoTool(tool));
            }
        }

        if (input.Context is not null)
        {
            foreach (var context in input.Context)
            {
                proto.Context.Add(new Proto.Context
                {
                    Description = context.Description,
                    Value = context.Value,
                });
            }
        }

        if (input.ForwardedProperties.ValueKind != JsonValueKind.Undefined)
        {
            proto.ForwardedProps = ProtoValueConverter.ToValue(input.ForwardedProperties);
        }

        if (input.Resume is not null)
        {
            foreach (var resume in input.Resume)
            {
                proto.Resume.Add(ToProtoResume(resume));
            }
        }

        return proto;
    }

    public static RunAgentInput FromProtoRunAgentInput(Proto.RunAgentInput proto)
    {
        var input = new RunAgentInput
        {
            ThreadId = proto.ThreadId,
            RunId = proto.RunId,
            ParentRunId = proto.HasParentRunId ? proto.ParentRunId : null,
            State = ProtoValueConverter.ToJsonElementOrNull(proto.State),
            ForwardedProperties = proto.ForwardedProps is null
                ? default
                : ProtoValueConverter.ToJsonElement(proto.ForwardedProps),
        };

        foreach (var message in proto.Messages)
        {
            input.Messages.Add(FromProto(message));
        }

        // The wire cannot tell an absent array from an empty one; present-empty
        // is the one form every layer accepts.
        var tools = new List<AGUITool>(proto.Tools.Count);
        foreach (var tool in proto.Tools)
        {
            tools.Add(FromProtoTool(tool));
        }

        input.Tools = tools;

        var contexts = new List<AGUIContext>(proto.Context.Count);
        foreach (var context in proto.Context)
        {
            contexts.Add(new AGUIContext { Description = context.Description, Value = context.Value });
        }

        input.Context = contexts;

        var resumes = new List<AGUIResume>(proto.Resume.Count);
        foreach (var resume in proto.Resume)
        {
            resumes.Add(FromProtoResume(resume));
        }

        input.Resume = resumes;

        return input;
    }

    private static Proto.Tool ToProtoTool(AGUITool tool)
    {
        var proto = new Proto.Tool
        {
            Name = tool.Name,
            Description = tool.Description ?? string.Empty,
            Metadata = ProtoValueConverter.ToStructOrNull(tool.Metadata),
        };

        if (tool.Parameters.ValueKind != JsonValueKind.Undefined)
        {
            proto.Parameters = ProtoValueConverter.ToValue(tool.Parameters);
        }

        return proto;
    }

    private static AGUITool FromProtoTool(Proto.Tool proto)
    {
        return new AGUITool
        {
            Name = proto.Name,
            Description = proto.Description,
            Parameters = proto.Parameters is null
                ? default
                : ProtoValueConverter.ToJsonElement(proto.Parameters),
            Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata),
        };
    }

    private static Proto.ResumeEntry ToProtoResume(AGUIResume resume)
    {
        var proto = new Proto.ResumeEntry
        {
            InterruptId = resume.InterruptId,
            Status = resume.Status,
            Metadata = ProtoValueConverter.ToStructOrNull(resume.Metadata),
        };

        if (resume.Payload is not null)
        {
            proto.Payload = ProtoValueConverter.ToValue(resume.Payload.Value);
        }

        return proto;
    }

    private static AGUIResume FromProtoResume(Proto.ResumeEntry proto)
    {
        return new AGUIResume
        {
            InterruptId = proto.InterruptId,
            Status = ProtoEventMapper.AssertOneOf(proto.Status, "status", ${closedSet("ResumeEntry", "status")}),
            Payload = ProtoValueConverter.ToJsonElementOrNull(proto.Payload),
            Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata),
        };
    }

    public static Proto.ToolCall ToProtoToolCall(AGUIToolCall toolCall)
    {
        var proto = new Proto.ToolCall
        {
            Id = toolCall.Id,
            Type = toolCall.Type,
            Metadata = ProtoValueConverter.ToStructOrNull(toolCall.Metadata),
            Function = new Proto.ToolCall.Types.Function
            {
                Name = toolCall.Function.Name,
                Arguments = toolCall.Function.Arguments,
            },
        };

        if (toolCall.EncryptedValue is not null)
        {
            proto.EncryptedValue = toolCall.EncryptedValue;
        }

        return proto;
    }

    public static AGUIToolCall FromProtoToolCall(Proto.ToolCall proto)
    {
        if (proto.Function is null)
        {
            throw ProtoEventMapper.MissingRequiredField("function");
        }

        return new AGUIToolCall
        {
            Id = proto.Id,
            Type = ProtoEventMapper.AssertOneOf(proto.Type, "type", ${closedSet("ToolCall", "type")}),
            Function = new AGUIToolCallFunction
            {
                Name = proto.Function.Name,
                Arguments = proto.Function.Arguments,
            },
            EncryptedValue = proto.HasEncryptedValue ? proto.EncryptedValue : null,
            Metadata = ProtoValueConverter.StructToJsonElementOrNull(proto.Metadata),
        };
    }

    public static Proto.Interrupt ToProtoInterrupt(AGUIInterrupt interrupt)
    {
        var proto = new Proto.Interrupt
        {
            Id = interrupt.Id,
            Reason = interrupt.Reason,
        };

        if (interrupt.Message is not null)
        {
            proto.Message = interrupt.Message;
        }

        if (interrupt.ToolCallId is not null)
        {
            proto.ToolCallId = interrupt.ToolCallId;
        }

        if (interrupt.ResponseSchema is not null)
        {
            proto.ResponseSchema = ProtoValueConverter.ToValue(interrupt.ResponseSchema.Value);
        }

        if (interrupt.ExpiresAt is not null)
        {
            proto.ExpiresAt = interrupt.ExpiresAt;
        }

        if (interrupt.Metadata is not null)
        {
            proto.Metadata = ProtoValueConverter.ToValue(interrupt.Metadata.Value);
        }

        return proto;
    }

    public static AGUIInterrupt FromProtoInterrupt(Proto.Interrupt proto)
    {
        return new AGUIInterrupt
        {
            Id = proto.Id,
            Reason = proto.Reason,
            Message = proto.HasMessage ? proto.Message : null,
            ToolCallId = proto.HasToolCallId ? proto.ToolCallId : null,
            ResponseSchema = ProtoValueConverter.ToJsonElementOrNull(proto.ResponseSchema),
            ExpiresAt = proto.HasExpiresAt ? proto.ExpiresAt : null,
            Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Metadata),
        };
    }

    public static Proto.JsonPatchOperation ToProtoPatchOperation(JsonElement operation)
    {
        var proto = new Proto.JsonPatchOperation
        {
            Op = ParseOperationType(GetStringProperty(operation, "op")),
            Path = GetStringProperty(operation, "path") ?? string.Empty,
        };

        if (operation.TryGetProperty("from", out var from) && from.ValueKind == JsonValueKind.String)
        {
            proto.From = from.GetString() ?? string.Empty;
        }

        if (operation.TryGetProperty("value", out var value) && value.ValueKind != JsonValueKind.Undefined)
        {
            proto.Value = ProtoValueConverter.ToValue(value);
        }

        return proto;
    }

    public static void WriteProtoPatchOperation(Utf8JsonWriter writer, Proto.JsonPatchOperation proto)
    {
        writer.WriteStartObject();
        writer.WriteString("op", OperationTypeToString(proto.Op));
        writer.WriteString("path", proto.Path);

        if (proto.HasFrom)
        {
            writer.WriteString("from", proto.From);
        }

        if (proto.Value is not null)
        {
            writer.WritePropertyName("value");
            ProtoValueConverter.WriteValue(writer, proto.Value);
        }

        writer.WriteEndObject();
    }

    private static Proto.InputContent? ToProtoContentPart(AGUIInputContent part)
    {
        switch (part)
        {
            case AGUITextInputContent text:
                return new Proto.InputContent
                {
                    Text = new Proto.TextInputPart { Text = text.Text },
                };
            case AGUIImageInputContent image:
                return new Proto.InputContent
                {
                    Image = new Proto.ImageInputPart
                    {
                        Source = ToProtoSource(image.Source),
                        Metadata = ProtoValueConverter.ToValueOrNull(image.Metadata),
                    },
                };
            case AGUIAudioInputContent audio:
                return new Proto.InputContent
                {
                    Audio = new Proto.AudioInputPart
                    {
                        Source = ToProtoSource(audio.Source),
                        Metadata = ProtoValueConverter.ToValueOrNull(audio.Metadata),
                    },
                };
            case AGUIVideoInputContent video:
                return new Proto.InputContent
                {
                    Video = new Proto.VideoInputPart
                    {
                        Source = ToProtoSource(video.Source),
                        Metadata = ProtoValueConverter.ToValueOrNull(video.Metadata),
                    },
                };
            case AGUIDocumentInputContent document:
                return new Proto.InputContent
                {
                    Document = new Proto.DocumentInputPart
                    {
                        Source = ToProtoSource(document.Source),
                        Metadata = ProtoValueConverter.ToValueOrNull(document.Metadata),
                    },
                };
            case AGUIBinaryInputContent binary:
            {
                // Legacy compatibility, predating the schema: the retired
                // "binary" part rides as a document part with marker metadata.
                var source = ToProtoBinarySource(binary);
                if (source is null)
                {
                    return null;
                }

                return new Proto.InputContent
                {
                    Document = new Proto.DocumentInputPart
                    {
                        Source = source,
                        Metadata = BuildBinaryMetadata(binary),
                    },
                };
            }
            default:
                return null;
        }
    }

    private static AGUIInputContent? FromProtoContentPart(Proto.InputContent proto)
    {
        switch (proto.PartCase)
        {
            case Proto.InputContent.PartOneofCase.Text:
                return new AGUITextInputContent { Text = proto.Text.Text };
            case Proto.InputContent.PartOneofCase.Image:
                return new AGUIImageInputContent
                {
                    Source = RequireSource(FromProtoSource(proto.Image.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Image.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Audio:
                return new AGUIAudioInputContent
                {
                    Source = RequireSource(FromProtoSource(proto.Audio.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Audio.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Video:
                return new AGUIVideoInputContent
                {
                    Source = RequireSource(FromProtoSource(proto.Video.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Video.Metadata),
                };
            case Proto.InputContent.PartOneofCase.Document:
                return new AGUIDocumentInputContent
                {
                    Source = RequireSource(FromProtoSource(proto.Document.Source)),
                    Metadata = ProtoValueConverter.ToJsonElementOrNull(proto.Document.Metadata),
                };
            case Proto.InputContent.PartOneofCase.None:
            default:
                return null;
        }
    }

    private static AGUIInputContentSource RequireSource(AGUIInputContentSource? source)
    {
        return source ?? throw new InvalidDataException(
            "Invalid event: a media content part carries no readable source.");
    }

    private static Proto.InputContentSource ToProtoSource(AGUIInputContentSource source)
    {
        switch (source)
        {
            case AGUIInputContentDataSource data:
                return new Proto.InputContentSource
                {
                    Data = new Proto.InputContentDataSource
                    {
                        Value = data.Value,
                        MimeType = data.MimeType,
                    },
                };
            case AGUIInputContentUrlSource url:
            {
                var urlSource = new Proto.InputContentUrlSource { Value = url.Value };
                if (url.MimeType is not null)
                {
                    urlSource.MimeType = url.MimeType;
                }

                return new Proto.InputContentSource { Url = urlSource };
            }
            default:
                throw new NotSupportedException(
                    $"Input content source type '{source.Type}' is not supported by the AG-UI protobuf wire format.");
        }
    }

    private static AGUIInputContentSource? FromProtoSource(Proto.InputContentSource? source)
    {
        if (source is null)
        {
            return null;
        }

        switch (source.SourceCase)
        {
            case Proto.InputContentSource.SourceOneofCase.Data:
                return new AGUIInputContentDataSource
                {
                    Value = source.Data.Value,
                    MimeType = source.Data.MimeType,
                };
            case Proto.InputContentSource.SourceOneofCase.Url:
                return new AGUIInputContentUrlSource
                {
                    Value = source.Url.Value,
                    MimeType = source.Url.HasMimeType ? source.Url.MimeType : null,
                };
            case Proto.InputContentSource.SourceOneofCase.None:
            default:
                return null;
        }
    }

    private static Proto.InputContentSource? ToProtoBinarySource(AGUIBinaryInputContent binary)
    {
        if (binary.Data is not null)
        {
            return new Proto.InputContentSource
            {
                Data = new Proto.InputContentDataSource { Value = binary.Data, MimeType = binary.MimeType },
            };
        }

        if (binary.Url is not null)
        {
            return new Proto.InputContentSource
            {
                Url = new Proto.InputContentUrlSource { Value = binary.Url, MimeType = binary.MimeType },
            };
        }

        if (binary.Id is not null)
        {
            return new Proto.InputContentSource
            {
                Url = new Proto.InputContentUrlSource { Value = binary.Id, MimeType = binary.MimeType },
            };
        }

        return null;
    }

    private static Value BuildBinaryMetadata(AGUIBinaryInputContent binary)
    {
        var metadata = new Struct();
        metadata.Fields["legacyBinary"] = new Value { BoolValue = true };
        metadata.Fields["filename"] = binary.Filename is null
            ? new Value { NullValue = NullValue.NullValue }
            : new Value { StringValue = binary.Filename };
        metadata.Fields["id"] = binary.Id is null
            ? new Value { NullValue = NullValue.NullValue }
            : new Value { StringValue = binary.Id };
        return new Value { StructValue = metadata };
    }

    private static Proto.JsonPatchOperationType ParseOperationType(string? op)
    {
        switch (op)
        {
${(defs.get("JsonPatchOperation") as { members: string[] }).members
  .map((member) => {
    const memberDef = objectDef(member);
    const discriminator = memberDef.fields.find((field) => field.name === "op");
    if (discriminator?.type.kind !== "literal") throw new Error("op literal");
    const value = discriminator.type.value;
    return `            case "${value}":
                return Proto.JsonPatchOperationType.${pascalCase(value)};`;
  })
  .join("\n")}
            default:
                throw new NotSupportedException(
                    $"JSON Patch operation '{op}' is not supported by the AG-UI protobuf wire format.");
        }
    }

    private static string OperationTypeToString(Proto.JsonPatchOperationType op)
    {
        switch (op)
        {
${(defs.get("JsonPatchOperation") as { members: string[] }).members
  .map((member) => {
    const memberDef = objectDef(member);
    const discriminator = memberDef.fields.find((field) => field.name === "op");
    if (discriminator?.type.kind !== "literal") throw new Error("op literal");
    const value = discriminator.type.value;
    return `            case Proto.JsonPatchOperationType.${pascalCase(value)}:
                return "${value}";`;
  })
  .join("\n")}
            default:
                // A wire value outside the enum must not invent an operation.
                throw new InvalidDataException(
                    $"Invalid event: unknown patch operation '{(int)op}'.");
        }
    }

    private static string? GetStringProperty(JsonElement element, string name)
    {
        if (element.ValueKind == JsonValueKind.Object &&
            element.TryGetProperty(name, out var value) &&
            value.ValueKind == JsonValueKind.String)
        {
            return value.GetString();
        }

        return null;
    }
}
`;

  return [
    { name: "ProtoEventMapper.g.cs", content: eventMapper },
    { name: "ProtoMessageMapper.g.cs", content: messageMapper },
    { name: "WireGuards.g.cs", content: wireGuards },
  ];
}
