/**
 * The Python emitter: model in, pydantic source out.
 *
 * Python idiom only — the model already resolved everything. Design mirrors
 * the handwritten SDK where the two agree (snake_case fields behind to_camel
 * aliases, EventType as a str Enum, Literal discriminators, Annotated
 * discriminated unions) and follows the schema where they differ: required
 * fields have no defaults, explicit null is rejected wherever the schema has
 * no null, and — the reason this target exists — the generated base model
 * omits valueless fields when serializing, by default, instead of each model
 * remembering to.
 *
 * If a field's meaning ever appears in this file, it has escaped the schema.
 */

import type {
  Definition,
  Field,
  ObjectDefinition,
  ProtocolModel,
  TypeExpr,
} from "./ir";

/** The one enum emitted as a Python Enum rather than a Literal alias. */
const PY_ENUM = "EventType";

const PYTHON_KEYWORDS = new Set([
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "while",
  "with",
  "yield",
]);

function banner(model: ProtocolModel): string {
  return [
    "# @generated by spec/generator — DO NOT EDIT.",
    `# Source: ${model.schemaId}`,
    "# Regenerate: pnpm --filter @ag-ui/spec generate",
    "",
  ].join("\n");
}

/** camelCase → snake_case, the exact inverse of pydantic's to_camel. */
function snakeCase(name: string): string {
  return name.replace(/([A-Z])/g, "_$1").toLowerCase();
}

/** The Python attribute for a wire field, dodging keywords with a suffix. */
function pythonName(wireName: string): string {
  const snake = snakeCase(wireName);
  return PYTHON_KEYWORDS.has(snake) ? `${snake}_` : snake;
}

function escapeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Wraps a description into an indented docstring. */
function docstring(description: string, indent: string): string {
  const width = 76 - indent.length;
  const words = description.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current === "" ? word : `${current} ${word}`;
    if (candidate.length > width && current !== "") {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current !== "") lines.push(current);
  if (lines.length === 1 && !lines[0].includes('"""')) {
    return `${indent}"""${lines[0]}"""`;
  }
  return [
    `${indent}"""`,
    ...lines.map((line) => `${indent}${line}`),
    `${indent}"""`,
  ].join("\n");
}

/** Renders a TypeExpr as a Python annotation. */
function pyType(type: TypeExpr): string {
  switch (type.kind) {
    case "string":
      return "str";
    case "integer":
      return "int";
    case "boolean":
      return "bool";
    case "literal":
      return type.enumRef === PY_ENUM
        ? `Literal[${PY_ENUM}.${type.value}]`
        : `Literal["${escapeString(type.value)}"]`;
    case "any":
      return "Any";
    case "openMap":
      return "Dict[str, Any]";
    case "stringEnum":
      return `Literal[${type.values
        .map((value) => `"${escapeString(value)}"`)
        .join(", ")}]`;
    case "ref":
      // Definitions are emitted in dependency order, so the target is always
      // already defined — no forward references, no rebuild step.
      return type.name;
    case "array":
      return `List[${pyType(type.items)}]`;
    case "union":
      return `Union[${type.members.map(pyType).join(", ")}]`;
  }
}

/** The Field(...) arguments a field's constraints and wiring need. */
function fieldArguments(field: Field, pyName: string): string[] {
  const args: string[] = [];
  if (!field.required) args.push("default=None");
  // The alias generator inverts snake_case back to the wire name; a keyword
  // dodge (from_) needs the alias spelled out.
  if (pyName !== snakeCase(field.name)) {
    args.push(`alias="${escapeString(field.name)}"`);
  }
  if (field.type.kind === "integer") {
    if (field.type.minimum !== undefined) args.push(`ge=${field.type.minimum}`);
    if (field.type.maximum !== undefined) args.push(`le=${field.type.maximum}`);
  }
  if (field.type.kind === "string" && field.type.pattern !== undefined) {
    args.push(`pattern=r"${field.type.pattern.replace(/"/g, '\\"')}"`);
  }
  if (field.type.kind === "array" && field.type.minItems !== undefined) {
    args.push(`min_length=${field.type.minItems}`);
  }
  return args;
}

function emitObject(definition: ObjectDefinition): string {
  const lines: string[] = [`class ${definition.name}(GeneratedBaseModel):`];
  lines.push(docstring(definition.description, "    "));
  lines.push("");

  for (const field of definition.fields) {
    const pyName = pythonName(field.name);
    const annotation = field.required
      ? pyType(field.type)
      : `Optional[${pyType(field.type)}]`;
    const args = fieldArguments(field, pyName);
    const description =
      field.type.kind === "array" && field.type.itemsDescription !== undefined
        ? `${field.description} Each item: ${field.type.itemsDescription}`
        : field.description;
    const value = args.length > 0 ? ` = Field(${args.join(", ")})` : "";
    lines.push(`    ${pyName}: ${annotation}${value}`);
    lines.push(docstring(description, "    "));
  }

  // An Optional annotation accepts an explicit null, which the schema does
  // not: on this wire null is not how absence is spelled. Required fields
  // reject null through their type; optional fields need a guard — except the
  // any-JSON ones, where null is data. (A wildcard validator is not an
  // option: pydantic forbids before-validators on discriminator fields.)
  const nullGuarded = definition.fields
    .filter(
      (field) =>
        !field.required && field.type.kind !== "any" && !refIsAny(field.type),
    )
    .map((field) => pythonName(field.name));
  if (nullGuarded.length > 0) {
    lines.push("");
    lines.push(
      `    @field_validator(${nullGuarded
        .map((name) => `"${name}"`)
        .join(", ")}, mode="before")`,
    );
    lines.push("    @classmethod");
    lines.push("    def _reject_null(cls, value: Any) -> Any:");
    lines.push("        if value is None:");
    lines.push(
      '            raise ValueError("null is not a value here; omit the field instead")',
    );
    lines.push("        return value");
  }
  return lines.join("\n");
}

/** Whether a ref field ultimately names an any alias (resolved by caller). */
let anyAliasNames = new Set<string>();
function refIsAny(type: TypeExpr): boolean {
  return type.kind === "ref" && anyAliasNames.has(type.name);
}

/** The Field(...) arguments a bare type's constraints need, field-agnostic. */
function constraintArguments(type: TypeExpr): string[] {
  const args: string[] = [];
  if (type.kind === "integer") {
    if (type.minimum !== undefined) args.push(`ge=${type.minimum}`);
    if (type.maximum !== undefined) args.push(`le=${type.maximum}`);
  }
  if (type.kind === "string" && type.pattern !== undefined) {
    args.push(`pattern=r"${type.pattern.replace(/"/g, '\\"')}"`);
  }
  if (type.kind === "array" && type.minItems !== undefined) {
    args.push(`min_length=${type.minItems}`);
  }
  return args;
}

/** An alias's annotation, keeping constraints a bare name would drop. */
function aliasAnnotation(type: TypeExpr): string {
  const args = constraintArguments(type);
  return args.length > 0
    ? `Annotated[${pyType(type)}, Field(${args.join(", ")})]`
    : pyType(type);
}

function emitDefinition(definition: Definition): string {
  switch (definition.kind) {
    case "object":
      return emitObject(definition);
    case "union": {
      const union = `Union[${definition.members.join(", ")}]`;
      const annotated =
        definition.discriminator !== undefined
          ? `Annotated[\n    ${union},\n    Field(discriminator="${definition.discriminator}"),\n]`
          : union;
      return [
        `${definition.name} = ${annotated}`,
        docstring(definition.description, ""),
      ].join("\n");
    }
    case "enum": {
      if (definition.name === PY_ENUM) {
        const members = definition.values
          .map((value) => `    ${value} = "${value}"`)
          .join("\n");
        return [
          `class ${definition.name}(str, Enum):`,
          docstring(definition.description, "    "),
          "",
          members,
        ].join("\n");
      }
      const values = definition.values
        .map((value) => `"${escapeString(value)}"`)
        .join(", ");
      return [
        `${definition.name} = Literal[${values}]`,
        docstring(definition.description, ""),
      ].join("\n");
    }
    case "alias":
      return [
        `${definition.name} = ${aliasAnnotation(definition.type)}`,
        docstring(definition.description, ""),
      ].join("\n");
  }
}

const BASE_MODEL = `class GeneratedBaseModel(BaseModel):
    """
    The generated base model. Wire names are camelCase behind snake_case
    attributes; unknown fields are kept, not dropped, so a boundary that wants
    to warn about them can still see them and a re-serialising intermediary
    does not lose them; and serialization omits fields that were never given
    a value — the default is omission, so no model has to remember it, while
    an explicit null that IS the data (a JSON Patch add of null) survives.
    Explicit null is rejected wherever the schema has no null: required
    fields reject it through their type, and each model guards its optional
    fields, because on this wire null is not how absence is spelled.
    """

    model_config = ConfigDict(
        extra="allow",
        alias_generator=to_camel,
        # Wire names only: accepting the snake_case attribute name as input
        # would invent meaning for a key the wire never defined — an unknown
        # message_id must land in the extras, not populate messageId.
        validate_by_alias=True,
        validate_by_name=False,
        # No lax coercion: the schema's "false" is not False and its "42" is
        # not 42. (Strict ints also reject 1.0, where JSON Schema accepts a
        # zero-fraction float — the rarer, safer direction.)
        strict=True,
    )

    def model_dump(self, **kwargs: Any) -> Any:
        kwargs.setdefault("exclude_unset", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs: Any) -> str:
        kwargs.setdefault("exclude_unset", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)`;

export function emitModels(model: ProtocolModel): string {
  anyAliasNames = new Set<string>();
  let grew = true;
  while (grew) {
    grew = false;
    for (const definition of model.definitions) {
      if (definition.kind !== "alias" || anyAliasNames.has(definition.name))
        continue;
      const target = definition.type;
      if (
        target.kind === "any" ||
        (target.kind === "ref" && anyAliasNames.has(target.name))
      ) {
        anyAliasNames.add(definition.name);
        grew = true;
      }
    }
  }

  const imports = [
    "from enum import Enum",
    "from typing import Annotated, Any, Dict, List, Literal, Optional, Union",
    "",
    "from pydantic import BaseModel, ConfigDict, Field, field_validator",
    "from pydantic.alias_generators import to_camel",
  ].join("\n");

  return [
    banner(model),
    imports,
    BASE_MODEL,
    ...model.definitions.map(emitDefinition),
    "",
  ].join("\n\n\n");
}

export function emitPythonVersion(model: ProtocolModel): string {
  return [
    banner(model),
    [
      `PROTOCOL_VERSION = "${escapeString(model.version)}"`,
      docstring(
        `The protocol version this code was generated from: the version segment of the schema's $id (${model.schemaId}). Never typed by a human.`,
        "",
      ),
    ].join("\n"),
    "",
  ].join("\n\n");
}

export function emitPythonInit(model: ProtocolModel): string {
  return [
    banner(model),
    docstring(
      "Generated models, alongside the handwritten ones. Non-public: nothing in ag_ui imports or re-exports this package, and its shape follows the schema rather than the handwritten API.",
      "",
    ),
    "",
  ].join("\n");
}

export interface GeneratedPythonFile {
  name: string;
  content: string;
}

export function emitPython(model: ProtocolModel): GeneratedPythonFile[] {
  return [
    { name: "__init__.py", content: emitPythonInit(model) },
    { name: "models.py", content: emitModels(model) },
    { name: "version.py", content: emitPythonVersion(model) },
  ];
}
