/**
 * The TypeScript emitter: model in, source text out.
 *
 * No interpretation happens here — the model already resolved composition,
 * requiredness, discriminators and documentation. This file decides TypeScript
 * idiom only: interfaces for objects, a TS enum for EventType (parity with the
 * handwritten SDK the output will one day replace), zod v4 via the `zod/v4`
 * subpath, `.looseObject` because the implementation layer is tolerant while
 * the spec stays strict, and `any` for the arbitrary-JSON positions.
 *
 * If a field's meaning ever appears in this file, it has escaped the schema.
 */

import type {
  Definition,
  Field,
  ObjectDefinition,
  ProtocolModel,
  TypeExpr,
} from "./ir";

/** The one enum emitted as a TS enum rather than a literal union. */
const TS_ENUM = "EventType";

function banner(model: ProtocolModel): string {
  return [
    "// @generated by spec/generator — DO NOT EDIT.",
    `// Source: ${model.schemaId}`,
    "// Regenerate: pnpm --filter @ag-ui/spec generate",
    "/* eslint-disable */",
    "",
  ].join("\n");
}

/** Wraps a description into a JSDoc block at a readable width. */
function jsdoc(
  description: string,
  extraTags: string[] = [],
  indent = "",
): string {
  const words = description.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current === "" ? word : `${current} ${word}`;
    if (candidate.length > 76 - indent.length && current !== "") {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current !== "") lines.push(current);
  const body = [...lines, ...extraTags];
  return [
    `${indent}/**`,
    ...body.map((line) => `${indent} * ${line}`),
    `${indent} */`,
  ].join("\n");
}

/** Renders a TypeExpr as a TypeScript type. */
function tsType(type: TypeExpr): string {
  switch (type.kind) {
    case "string":
      return "string";
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "literal":
      return type.enumRef === TS_ENUM
        ? `${TS_ENUM}.${type.value}`
        : JSON.stringify(type.value);
    case "any":
      return "any";
    case "openMap":
      return "Record<string, any>";
    case "stringEnum":
      return type.values.map((value) => JSON.stringify(value)).join(" | ");
    case "ref":
      return type.name;
    case "array": {
      const items = tsType(type.items);
      const needsParens =
        type.items.kind === "union" || type.items.kind === "stringEnum";
      return needsParens ? `(${items})[]` : `${items}[]`;
    }
    case "union":
      return type.members.map(tsType).join(" | ");
  }
}

function fieldTags(field: Field): string[] {
  const tags: string[] = [];
  if (field.defaultValue !== undefined) {
    tags.push(`@default ${JSON.stringify(field.defaultValue)}`);
  }
  if (field.contentEncoding !== undefined) {
    tags.push(`@contentEncoding ${field.contentEncoding}`);
  }
  return tags;
}

function emitInterface(definition: ObjectDefinition): string {
  const fields = definition.fields
    .map((field) => {
      const description =
        field.type.kind === "array" && field.type.itemsDescription !== undefined
          ? `${field.description} Each item: ${field.type.itemsDescription}`
          : field.description;
      const doc = jsdoc(description, fieldTags(field), "  ");
      const optional = field.required ? "" : "?";
      return `${doc}\n  ${field.name}${optional}: ${tsType(field.type)};`;
    })
    .join("\n");
  return `${jsdoc(definition.description)}\nexport interface ${definition.name} {\n${fields}\n}`;
}

function emitTypeDefinition(definition: Definition): string {
  switch (definition.kind) {
    case "object":
      return emitInterface(definition);
    case "union":
      return `${jsdoc(definition.description)}\nexport type ${definition.name} =\n${definition.members
        .map((member) => `  | ${member}`)
        .join("\n")};`;
    case "enum": {
      if (definition.name === TS_ENUM) {
        const members = definition.values
          .map((value) => `  ${value} = ${JSON.stringify(value)},`)
          .join("\n");
        return `${jsdoc(definition.description)}\nexport enum ${definition.name} {\n${members}\n}`;
      }
      const members = definition.values.map((value) => JSON.stringify(value));
      return `${jsdoc(definition.description)}\nexport type ${definition.name} = ${members.join(" | ")};`;
    }
    case "alias":
      return `${jsdoc(definition.description)}\nexport type ${definition.name} = ${tsType(definition.type)};`;
  }
}

export function emitTypes(model: ProtocolModel): string {
  return [banner(model), ...model.definitions.map(emitTypeDefinition), ""].join(
    "\n\n",
  );
}

/** Renders a TypeExpr as a zod v4 expression. */
function zodType(type: TypeExpr): string {
  switch (type.kind) {
    case "string": {
      let expr = "z.string()";
      if (type.pattern !== undefined) {
        expr += `.regex(new RegExp(${JSON.stringify(type.pattern)}))`;
      }
      return expr;
    }
    case "integer": {
      let expr = "z.int()";
      if (type.minimum !== undefined) expr += `.min(${type.minimum})`;
      if (type.maximum !== undefined) expr += `.max(${type.maximum})`;
      return expr;
    }
    case "boolean":
      return "z.boolean()";
    case "literal":
      return type.enumRef === TS_ENUM
        ? `z.literal(${TS_ENUM}.${type.value})`
        : `z.literal(${JSON.stringify(type.value)})`;
    case "any":
      return "z.any()";
    case "openMap":
      // Not z.record: its key schema rejects prototype-named keys such as
      // "constructor", which are valid JSON the spec accepts. z.custom checks
      // "plain object" and passes the value through untouched.
      return (
        "z.custom<Record<string, any>>(" +
        '(value) => typeof value === "object" && value !== null && !Array.isArray(value)' +
        ")"
      );
    case "stringEnum":
      return `z.enum([${type.values.map((value) => JSON.stringify(value)).join(", ")}])`;
    case "ref":
      return `${type.name}Schema`;
    case "array": {
      let expr = `z.array(${zodType(type.items)})`;
      if (type.minItems !== undefined) expr += `.min(${type.minItems})`;
      return expr;
    }
    case "union":
      return `z.union([${type.members.map(zodType).join(", ")}])`;
  }
}

function emitSchemaDefinition(
  definition: Definition,
  anyAliases: Set<string>,
): string {
  const doc = jsdoc(definition.description);
  switch (definition.kind) {
    case "object": {
      const fields = definition.fields
        .map((field) => {
          // zod treats a property whose schema accepts undefined as an
          // optional key, so a required arbitrary-JSON field needs an explicit
          // presence check or a missing key would parse.
          const acceptsUndefined =
            field.type.kind === "any" ||
            (field.type.kind === "ref" && anyAliases.has(field.type.name));
          const presence =
            field.required && acceptsUndefined
              ? ".refine((value) => value !== undefined)"
              : "";
          const optional = field.required ? "" : ".optional()";
          return `  ${field.name}: ${zodType(field.type)}${presence}${optional},`;
        })
        .join("\n");
      // looseObject on purpose: the spec is strict, the implementation is
      // tolerant, and the middleware that warns and strips needs the unknown
      // keys to survive the parse.
      return `${doc}\nexport const ${definition.name}Schema = z.looseObject({\n${fields}\n});`;
    }
    case "union": {
      const members = definition.members.map((member) => `${member}Schema`);
      const expr =
        definition.discriminator !== undefined
          ? `z.discriminatedUnion(${JSON.stringify(definition.discriminator)}, [\n${members
              .map((member) => `  ${member},`)
              .join("\n")}\n])`
          : `z.union([\n${members.map((member) => `  ${member},`).join("\n")}\n])`;
      return `${doc}\nexport const ${definition.name}Schema = ${expr};`;
    }
    case "enum": {
      const expr =
        definition.name === TS_ENUM
          ? `z.enum(${TS_ENUM})`
          : `z.enum([${definition.values.map((value) => JSON.stringify(value)).join(", ")}])`;
      return `${doc}\nexport const ${definition.name}Schema = ${expr};`;
    }
    case "alias":
      return `${doc}\nexport const ${definition.name}Schema = ${zodType(definition.type)};`;
  }
}

export function emitSchemas(model: ProtocolModel): string {
  const usesEnum = model.definitions.some(
    (definition) => definition.kind === "enum" && definition.name === TS_ENUM,
  );
  const imports = [
    `import { z } from "zod/v4";`,
    ...(usesEnum ? [`import { ${TS_ENUM} } from "./types";`] : []),
  ].join("\n");
  // Transitive: an alias of an alias of any accepts undefined just the same.
  const anyAliases = new Set<string>();
  let grew = true;
  while (grew) {
    grew = false;
    for (const definition of model.definitions) {
      if (definition.kind !== "alias" || anyAliases.has(definition.name))
        continue;
      const target = definition.type;
      if (
        target.kind === "any" ||
        (target.kind === "ref" && anyAliases.has(target.name))
      ) {
        anyAliases.add(definition.name);
        grew = true;
      }
    }
  }
  return [
    banner(model),
    imports,
    ...model.definitions.map((definition) =>
      emitSchemaDefinition(definition, anyAliases),
    ),
    "",
  ].join("\n\n");
}

export function emitVersion(model: ProtocolModel): string {
  const doc = jsdoc(
    `The protocol version this code was generated from: the version segment of the schema's $id (${model.schemaId}). Never typed by a human.`,
  );
  return [
    banner(model),
    `${doc}\nexport const PROTOCOL_VERSION = ${JSON.stringify(model.version)};`,
    "",
  ].join("\n\n");
}

export function emitAgreement(model: ProtocolModel): string {
  const preamble = `import type { z } from "zod/v4";
import type * as t from "./types";
import type * as s from "./schemas";

/**
 * Type-level agreement between the interfaces and the zod schemas: the two are
 * emitted independently, so a generator bug that makes one field optional in
 * one and required in the other would otherwise ship silently. Each assertion
 * compares the schema's inferred output with the interface, after stripping
 * looseObject's own index signature (its value is exactly unknown) while
 * keeping the open-by-key positions' index signatures (their value is any),
 * so records stay compared and only the passthrough artefact is ignored. A
 * mismatch is a compile error on every build of this package.
 */
type IsAny<T> = 0 extends 1 & T ? true : false;
type DeepClean<T> =
  IsAny<T> extends true
    ? T
    : T extends readonly (infer U)[]
      ? DeepClean<U>[]
      : T extends object
        ? {
            [K in keyof T as string extends K
              ? unknown extends T[K]
                ? IsAny<T[K]> extends true
                  ? K
                  : never
                : K
              : K]: DeepClean<T[K]>;
          }
        : T;
type Equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? true
    : false;
type Expect<T extends true> = T;`;

  const checks = model.definitions
    .map((definition) => {
      // A TS enum type and the union of its member types are the same values
      // but distinct to TypeScript's type identity, so the enum's check
      // compares against the member union rather than the enum type name.
      const expected =
        definition.kind === "enum" && definition.name === TS_ENUM
          ? `(typeof t.${TS_ENUM})[keyof typeof t.${TS_ENUM}]`
          : `DeepClean<t.${definition.name}>`;
      return `type _${definition.name} = Expect<Equal<DeepClean<z.infer<typeof s.${definition.name}Schema>>, ${expected}>>;`;
    })
    .join("\n");

  return [banner(model), preamble, checks, "export {};", ""].join("\n\n");
}

export interface GeneratedFile {
  name: string;
  content: string;
}

export function emitTypeScript(model: ProtocolModel): GeneratedFile[] {
  return [
    { name: "types.ts", content: emitTypes(model) },
    { name: "schemas.ts", content: emitSchemas(model) },
    { name: "version.ts", content: emitVersion(model) },
    { name: "agreement.ts", content: emitAgreement(model) },
  ];
}
