// @generated by spec/generator — DO NOT EDIT.
// Source: https://ag-ui.com/spec/draft/schema.json
// Regenerate: pnpm --filter @ag-ui/spec generate

import { BaseEvent, AGUIEvent, EventSchemas, EventType } from "@ag-ui/core";
import * as protoEvents from "./generated/events";
import * as protoPatch from "./generated/patch";

/**
 * These converters run against values that have crossed a wire boundary, so
 * they accept `unknown` and narrow once rather than trusting a static type.
 */
type LooseRecord = Record<string, unknown>;

const asRecord = (value: unknown): LooseRecord | undefined =>
  value && typeof value === "object" ? (value as LooseRecord) : undefined;

const asArray = (value: unknown): unknown[] => (Array.isArray(value) ? value : []);

function toCamelCase(str: string): string {
  return str.toLowerCase().replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
}

/**
 * The event types the handwritten SDK models know. The schema — and this
 * generated wire layer — can be ahead of them; an event outside this set is
 * carried structurally and validated once the SDK catches up.
 */
const KNOWN_TO_CORE = new Set<string>(Object.values(EventType));

/**
 * The envelope's oneof entry names, mapped to the event type each carries.
 * The entry selected the message shape, so it is authoritative on decode.
 */
const ENVELOPE_TYPE: Record<string, string | undefined> = {
  textMessageStart: "TEXT_MESSAGE_START",
  textMessageContent: "TEXT_MESSAGE_CONTENT",
  textMessageEnd: "TEXT_MESSAGE_END",
  textMessageChunk: "TEXT_MESSAGE_CHUNK",
  toolCallStart: "TOOL_CALL_START",
  toolCallArgs: "TOOL_CALL_ARGS",
  toolCallEnd: "TOOL_CALL_END",
  toolCallChunk: "TOOL_CALL_CHUNK",
  toolCallResult: "TOOL_CALL_RESULT",
  stateSnapshot: "STATE_SNAPSHOT",
  stateDelta: "STATE_DELTA",
  messagesSnapshot: "MESSAGES_SNAPSHOT",
  activitySnapshot: "ACTIVITY_SNAPSHOT",
  activityDelta: "ACTIVITY_DELTA",
  raw: "RAW",
  custom: "CUSTOM",
  runStarted: "RUN_STARTED",
  runFinished: "RUN_FINISHED",
  runError: "RUN_ERROR",
  stepStarted: "STEP_STARTED",
  stepFinished: "STEP_FINISHED",
  reasoningStart: "REASONING_START",
  reasoningMessageStart: "REASONING_MESSAGE_START",
  reasoningMessageContent: "REASONING_MESSAGE_CONTENT",
  reasoningMessageEnd: "REASONING_MESSAGE_END",
  reasoningMessageChunk: "REASONING_MESSAGE_CHUNK",
  reasoningEnd: "REASONING_END",
  reasoningEncryptedValue: "REASONING_ENCRYPTED_VALUE",
  subagentStarted: "SUBAGENT_STARTED",
  subagentFinished: "SUBAGENT_FINISHED",
  subagentError: "SUBAGENT_ERROR",
};
/** The envelope's known field numbers, for the repeated-tag scan. */
const ENVELOPE_TAGS = new Set<number>([
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
  28, 29, 30, 31,
]);

/**
 * Narrows metadata to the object the wire format declares, or nothing.
 *
 * On the validated path the schema has already guaranteed this. On the fallback
 * path below the event is unvalidated, and the generated `Struct.wrap` would
 * quietly mangle anything else — an array becomes `{"0": …}`, a string becomes
 * per-character keys, a number becomes `{}`. Dropping the value is the honest
 * outcome for a shim whose contract is to warn and encode best-effort; the
 * caller already gets a loud warning naming the validation failure.
 */
const normalizeMetadata = (metadata: unknown): LooseRecord | undefined =>
  typeof metadata === "object" && metadata !== null && !Array.isArray(metadata)
    ? (metadata as LooseRecord)
    : undefined;

const toProtoSource = (source: unknown): unknown => {
  const rec = asRecord(source);
  if (!rec) return undefined;
  if (rec.type === "data") {
    return { data: { value: rec.value, mimeType: rec.mimeType } };
  }
  if (rec.type === "url") {
    return { url: { value: rec.value, mimeType: rec.mimeType } };
  }
  return undefined;
};

const fromProtoSource = (source: unknown): unknown => {
  const rec = asRecord(source);
  if (!rec) return undefined;
  // Exactly one populated arm: a source carrying several is malformed, and
  // picking one would silently discard the rest.
  if ([rec.data, rec.url].filter(Boolean).length > 1) {
    throw new Error("Invalid event: source carries more than one arm");
  }
  if (rec.data) {
    const wire = rec.data as LooseRecord;
    return { type: "data", value: wire.value, mimeType: wire.mimeType };
  }
  if (rec.url) {
    const wire = rec.url as LooseRecord;
    return { type: "url", value: wire.value, mimeType: wire.mimeType };
  }
  return undefined;
};

const toProtoContentPart = (part: unknown): unknown => {
  const rec = asRecord(part);
  if (!rec) return undefined;

  switch (rec.type) {
    case "text":
      return { text: { text: rec.text } };
    case "image":
      return { image: { source: toProtoSource(rec.source), metadata: rec.metadata } };
    case "audio":
      return { audio: { source: toProtoSource(rec.source), metadata: rec.metadata } };
    case "video":
      return { video: { source: toProtoSource(rec.source), metadata: rec.metadata } };
    case "document":
      return { document: { source: toProtoSource(rec.source), metadata: rec.metadata } };
    // Legacy compatibility, predating the schema: the retired "binary" part
    // rides as a document part with marker metadata. Behavioural rule of this
    // layer, not a schema fact.
    case "binary": {
      const source = rec.data
        ? { data: { value: rec.data, mimeType: rec.mimeType } }
        : rec.url
          ? { url: { value: rec.url, mimeType: rec.mimeType } }
          : rec.id
            ? { url: { value: rec.id, mimeType: rec.mimeType } }
            : undefined;
      if (!source) return undefined;
      return {
        document: {
          source,
          metadata: { legacyBinary: true, filename: rec.filename, id: rec.id },
        },
      };
    }
    default:
      return undefined;
  }
};

const fromProtoContentPart = (part: unknown): unknown => {
  const rec = asRecord(part);
  if (!rec) return undefined;
  // Exactly one populated arm, as with the source above.
  if ([rec.text, rec.image, rec.audio, rec.video, rec.document].filter(Boolean).length > 1) {
    throw new Error("Invalid event: content part carries more than one arm");
  }
  if (rec.text) {
    const part = rec.text as LooseRecord;
    return { type: "text", text: part.text };
  }
  if (rec.image) {
    const part = rec.image as LooseRecord;
    return { type: "image", source: fromProtoSource(part.source), metadata: part.metadata };
  }
  if (rec.audio) {
    const part = rec.audio as LooseRecord;
    return { type: "audio", source: fromProtoSource(part.source), metadata: part.metadata };
  }
  if (rec.video) {
    const part = rec.video as LooseRecord;
    return { type: "video", source: fromProtoSource(part.source), metadata: part.metadata };
  }
  if (rec.document) {
    const part = rec.document as LooseRecord;
    return { type: "document", source: fromProtoSource(part.source), metadata: part.metadata };
  }
  return undefined;
};

/**
 * The wire's one Message carries the union of every role's fields; which
 * field feeds `content` depends on the role.
 */
const MAP_CONTENT_ROLES = new Set<string>(["activity"]);
const PARTS_CONTENT_ROLES = new Set<string>(["user"]);

const toWireMessage = (value: unknown): LooseRecord => {
  const message = asRecord(value) ?? {};
  const wire: LooseRecord = { ...message, contentParts: [] };
  wire.metadata = normalizeMetadata(message.metadata);
  wire.toolCalls = asArray(message.toolCalls).map((toolCall: unknown) => ({
    ...(toolCall as LooseRecord),
    metadata: normalizeMetadata(asRecord(toolCall)?.metadata),
  }));
  if (Array.isArray(message.content)) {
    wire.contentParts = message.content
      .map((part: unknown) => toProtoContentPart(part))
      .filter((part: unknown) => part !== undefined);
    wire.content = undefined;
  } else if (typeof message.role === "string" && MAP_CONTENT_ROLES.has(message.role)) {
    wire.activityContent = normalizeMetadata(message.content) ?? {};
    wire.content = undefined;
  }
  return wire;
};

const fromWireMessage = (value: unknown): LooseRecord => {
  const wire = asRecord(value) ?? {};
  const message: LooseRecord = { ...wire };
  const role = typeof wire.role === "string" ? wire.role : "";
  // Content carriers are role-exclusive; a message carrying a carrier its
  // role does not use would lose data whichever one decode preferred.
  if (!PARTS_CONTENT_ROLES.has(role) && asArray(wire.contentParts).length > 0) {
    throw new Error("Invalid event: message carries content parts for a role that has none");
  }
  if (wire.activityContent !== undefined && !MAP_CONTENT_ROLES.has(role)) {
    throw new Error("Invalid event: message carries activity content for a non-activity role");
  }
  if (MAP_CONTENT_ROLES.has(role) && wire.content !== undefined) {
    throw new Error("Invalid event: activity content cannot ride with other content forms");
  }
  if (
    PARTS_CONTENT_ROLES.has(role) &&
    wire.content !== undefined &&
    asArray(wire.contentParts).length > 0
  ) {
    // String content and parts together is a contradiction the encoder never
    // writes; resolving it either way would silently discard the other half.
    throw new Error("Invalid event: message carries both string content and content parts");
  }
  if (PARTS_CONTENT_ROLES.has(role) && wire.content === undefined) {
    // String content rides the content field; anything else is the parts
    // array — including an empty one, which is valid content of its own. A
    // part with no recognisable arm is rejected, not erased: the JSON path
    // rejects an unknown part type too, and a vanishing image changes what
    // the message says.
    message.content = asArray(wire.contentParts).map((part: unknown) => {
      const converted = fromProtoContentPart(part);
      if (converted === undefined) {
        throw new Error("Invalid event: unreadable content part");
      }
      return converted;
    });
  }
  if (MAP_CONTENT_ROLES.has(role) && wire.activityContent !== undefined) {
    message.content = wire.activityContent;
  }
  delete message.activityContent;
  delete message.contentParts;
  if (asArray(wire.toolCalls).length === 0) {
    delete message.toolCalls;
  }
  Object.keys(message).forEach((key) => {
    if (message[key] === undefined) delete message[key];
  });
  return message;
};

/**
 * ts-proto materialises absent optional fields as undefined-valued keys, on
 * nested objects too. An absent field stays absent: the keys go.
 */
const dropUndefinedDeep = (value: unknown): void => {
  if (Array.isArray(value)) {
    for (const entry of value) dropUndefinedDeep(entry);
    return;
  }
  const rec = asRecord(value);
  if (!rec) return;
  for (const key of Object.keys(rec)) {
    if (rec[key] === undefined) {
      delete rec[key];
    } else {
      dropUndefinedDeep(rec[key]);
    }
  }
};

const normalizeItemMetadata = (value: unknown): LooseRecord => ({
  ...(asRecord(value) ?? {}),
  metadata: normalizeMetadata(asRecord(value)?.metadata),
});

const toWireRunAgentInput = (value: unknown): LooseRecord | undefined => {
  const input = asRecord(value);
  if (!input) return undefined;
  return {
    threadId: input.threadId,
    runId: input.runId,
    parentRunId: input.parentRunId,
    state: input.state,
    messages: asArray(input.messages).map(toWireMessage),
    tools: asArray(input.tools).map(normalizeItemMetadata),
    context: asArray(input.context),
    forwardedProps: input.forwardedProps,
    resume: asArray(input.resume).map(normalizeItemMetadata),
  };
};

const fromWireRunAgentInput = (value: unknown): LooseRecord | undefined => {
  const rec = asRecord(value);
  if (!rec) return undefined;
  const output: LooseRecord = {};
  if (rec.threadId !== undefined) output.threadId = rec.threadId;
  if (rec.runId !== undefined) output.runId = rec.runId;
  if (rec.parentRunId !== undefined) output.parentRunId = rec.parentRunId;
  if (rec.state !== undefined) output.state = rec.state;
  output.messages = asArray(rec.messages).map(fromWireMessage);
  output.tools = asArray(rec.tools);
  output.context = asArray(rec.context);
  if (rec.forwardedProps !== undefined) output.forwardedProps = rec.forwardedProps;
  output.resume = asArray(rec.resume);
  return output;
};

/**
 * Encodes an event to the protobuf wire format.
 */
export function encode(event: BaseEvent): Uint8Array {
  // Events the handwritten SDK knows are validated, with a warning and a
  // best-effort fallback for malformed ones — existing clients encoding
  // invalid events keep working, loudly. Events the SDK does not know yet
  // (the schema can be ahead of it) are carried structurally.
  let validatedEvent: AGUIEvent | BaseEvent = event;
  if (KNOWN_TO_CORE.has(event.type as string)) {
    try {
      validatedEvent = EventSchemas.parse(event) as AGUIEvent;
    } catch (err) {
      console.warn(
        "[ag-ui][proto.encode] Malformed event detected, falling back to unvalidated event",
        err,
        event,
      );
      validatedEvent = event;
    }
  }
  const oneofField = toCamelCase(validatedEvent.type as string);
  const { type, timestamp, rawEvent, metadata, ...rest } = validatedEvent as unknown as LooseRecord;

  if (type === "MESSAGES_SNAPSHOT" && Array.isArray(rest.messages)) {
    rest.messages = rest.messages.map(toWireMessage);
  }
  if (type === "RUN_FINISHED") {
    const outcomeRecord = asRecord(rest.outcome);
    rest.interrupts = [];
    if (rest.outcome === undefined) {
      rest.outcome = "";
    } else if (outcomeRecord?.type === "success") {
      rest.outcome = "success";
    } else if (outcomeRecord?.type === "interrupt") {
      rest.outcome = "interrupt";
      rest.interrupts = asArray(outcomeRecord?.interrupts);
    } else {
      rest.outcome = typeof outcomeRecord?.type === "string" ? outcomeRecord.type : "";
    }
  }
  if (type === "SUBAGENT_FINISHED") {
    const outcomeRecord = asRecord(rest.outcome);
    rest.interruptIds = [];
    if (rest.outcome === undefined) {
      rest.outcome = "";
    } else if (outcomeRecord?.type === "success") {
      rest.outcome = "success";
    } else if (outcomeRecord?.type === "suspended") {
      rest.outcome = "suspended";
      rest.interruptIds = asArray(outcomeRecord?.interruptIds);
    } else {
      rest.outcome = typeof outcomeRecord?.type === "string" ? outcomeRecord.type : "";
    }
  }
  if (type === "STATE_DELTA" && Array.isArray(rest.delta)) {
    rest.delta = (rest.delta as LooseRecord[]).map((operation) => ({
      ...operation,
      // Cast, not coercion: String(op) would turn malformed values such as
      // ["add"] into a valid enum member, where this throws instead.
      op: protoPatch.JsonPatchOperationType[
        (operation.op as string).toUpperCase() as keyof typeof protoPatch.JsonPatchOperationType
      ],
    }));
  }
  if (type === "ACTIVITY_DELTA" && Array.isArray(rest.patch)) {
    rest.patch = (rest.patch as LooseRecord[]).map((operation) => ({
      ...operation,
      // Cast, not coercion: String(op) would turn malformed values such as
      // ["add"] into a valid enum member, where this throws instead.
      op: protoPatch.JsonPatchOperationType[
        (operation.op as string).toUpperCase() as keyof typeof protoPatch.JsonPatchOperationType
      ],
    }));
  }
  if (type === "RUN_FINISHED") {
    rest.usage = asArray(rest.usage);
  }
  if (type === "RUN_ERROR") {
    rest.usage = asArray(rest.usage);
  }
  if (type === "RUN_STARTED" && rest.input !== undefined) {
    rest.input = toWireRunAgentInput(rest.input);
  }

  const eventMessage = {
    [oneofField]: {
      baseEvent: {
        type: protoEvents.EventType[event.type as keyof typeof protoEvents.EventType],
        timestamp,
        rawEvent,
        metadata: normalizeMetadata(metadata),
      },
      ...rest,
    },
  };
  return protoEvents.Event.encode(eventMessage).finish();
}

/**
 * Decodes the protobuf wire format to an event.
 */
/**
 * One message level of the malformed-wire scan: which singular message-typed
 * fields may not repeat (canonical protobuf merges them, ts-proto — this
 * runtime — replaces), which fields to descend into, and which oneof arms
 * are mutually exclusive. google.protobuf.* payloads are counted but not
 * entered: their insides belong to the runtime library, a recorded boundary.
 */
interface ScanSpec {
  singular: Set<number>;
  descend: Record<number, string | undefined>;
  arms?: Set<number>;
}

const SCAN_SPECS: Record<string, ScanSpec | undefined> = {
  TextMessageStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  BaseEvent: { singular: new Set([3, 4]), descend: {} },
  TextMessageContentEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  TextMessageEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallArgsEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  StateSnapshotEvent: { singular: new Set([1, 2]), descend: { 1: "BaseEvent" } },
  StateDeltaEvent: { singular: new Set([1]), descend: { 1: "BaseEvent", 2: "JsonPatchOperation" } },
  JsonPatchOperation: { singular: new Set([4]), descend: {} },
  MessagesSnapshotEvent: { singular: new Set([1]), descend: { 1: "BaseEvent", 2: "Message" } },
  Message: { singular: new Set([9, 13]), descend: { 5: "ToolCall", 8: "InputContent" } },
  ToolCall: { singular: new Set([3, 4]), descend: {} },
  InputContent: {
    singular: new Set([1, 2, 3, 4, 5]),
    descend: {
      2: "ImageInputPart",
      3: "AudioInputPart",
      4: "VideoInputPart",
      5: "DocumentInputPart",
    },
    arms: new Set([1, 2, 3, 4, 5]),
  },
  ImageInputPart: { singular: new Set([1, 2]), descend: { 1: "InputContentSource" } },
  InputContentSource: { singular: new Set([1, 2]), descend: {}, arms: new Set([1, 2]) },
  AudioInputPart: { singular: new Set([1, 2]), descend: { 1: "InputContentSource" } },
  VideoInputPart: { singular: new Set([1, 2]), descend: { 1: "InputContentSource" } },
  DocumentInputPart: { singular: new Set([1, 2]), descend: { 1: "InputContentSource" } },
  RawEvent: { singular: new Set([1, 2]), descend: { 1: "BaseEvent" } },
  CustomEvent: { singular: new Set([1, 3]), descend: { 1: "BaseEvent" } },
  RunStartedEvent: { singular: new Set([1, 5]), descend: { 1: "BaseEvent", 5: "RunAgentInput" } },
  RunAgentInput: {
    singular: new Set([4, 8]),
    descend: { 5: "Message", 6: "Tool", 9: "ResumeEntry" },
  },
  Tool: { singular: new Set([3, 4]), descend: {} },
  ResumeEntry: { singular: new Set([3, 4]), descend: {} },
  RunFinishedEvent: { singular: new Set([1, 4]), descend: { 1: "BaseEvent", 6: "Interrupt" } },
  Interrupt: { singular: new Set([5, 7]), descend: {} },
  RunErrorEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  StepStartedEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  StepFinishedEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  TextMessageChunkEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallChunkEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ToolCallResultEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ActivitySnapshotEvent: { singular: new Set([1, 5]), descend: { 1: "BaseEvent" } },
  ActivityDeltaEvent: {
    singular: new Set([1]),
    descend: { 1: "BaseEvent", 5: "JsonPatchOperation" },
  },
  ReasoningStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageStartEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageContentEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningMessageChunkEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningEndEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  ReasoningEncryptedValueEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  SubagentStartedEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
  SubagentFinishedEvent: { singular: new Set([1, 3]), descend: { 1: "BaseEvent" } },
  SubagentErrorEvent: { singular: new Set([1]), descend: { 1: "BaseEvent" } },
};

/** Envelope entry number -> event message name, all descended into. */
const ENVELOPE_SCAN: Record<number, string | undefined> = {
  1: "TextMessageStartEvent",
  2: "TextMessageContentEvent",
  3: "TextMessageEndEvent",
  4: "ToolCallStartEvent",
  5: "ToolCallArgsEvent",
  6: "ToolCallEndEvent",
  7: "StateSnapshotEvent",
  8: "StateDeltaEvent",
  9: "MessagesSnapshotEvent",
  10: "RawEvent",
  11: "CustomEvent",
  12: "RunStartedEvent",
  13: "RunFinishedEvent",
  14: "RunErrorEvent",
  15: "StepStartedEvent",
  16: "StepFinishedEvent",
  17: "TextMessageChunkEvent",
  18: "ToolCallChunkEvent",
  19: "ToolCallResultEvent",
  20: "ActivitySnapshotEvent",
  21: "ActivityDeltaEvent",
  22: "ReasoningStartEvent",
  23: "ReasoningMessageStartEvent",
  24: "ReasoningMessageContentEvent",
  25: "ReasoningMessageEndEvent",
  26: "ReasoningMessageChunkEvent",
  27: "ReasoningEndEvent",
  28: "ReasoningEncryptedValueEvent",
  29: "SubagentStartedEvent",
  30: "SubagentFinishedEvent",
  31: "SubagentErrorEvent",
};

// Mirrors the wire reader's uint32 truncation exactly: the fifth byte
// contributes only its low four bits, later bytes none — otherwise an
// overlong encoding of a tag would dodge duplicate detection while the
// real decoder still reads the canonical field number.
function readVarint(data: Uint8Array, cursor: { offset: number }): number {
  let result = 0;
  let shift = 0;
  for (;;) {
    if (cursor.offset >= data.length) throw new Error("Invalid event");
    const byte = data[cursor.offset++];
    if (shift < 28) result += (byte & 0x7f) * 2 ** shift;
    else if (shift === 28) result += (byte & 0x0f) * 2 ** 28;
    shift += 7;
    if ((byte & 0x80) === 0) return result;
  }
}

/** Walks one message level of the scan graph, recursing along descend edges. */
function scanMessage(data: Uint8Array, spec: ScanSpec): void {
  const cursor = { offset: 0 };
  let groupDepth = 0;
  const seenSingular = new Set<number>();
  let seenArm = 0;
  while (cursor.offset < data.length) {
    const tag = readVarint(data, cursor);
    const field = Math.floor(tag / 8);
    const wireType = tag % 8;
    if (field === 0) {
      throw new Error("Invalid event");
    }
    if (wireType === 3) {
      groupDepth += 1;
      continue;
    }
    if (wireType === 4) {
      groupDepth -= 1;
      if (groupDepth < 0) throw new Error("Invalid event");
      continue;
    }
    if (wireType === 0) {
      readVarint(data, cursor);
    } else if (wireType === 1) {
      cursor.offset += 8;
    } else if (wireType === 2) {
      const length = readVarint(data, cursor);
      if (cursor.offset + length > data.length) throw new Error("Invalid event");
      if (groupDepth === 0) {
        if (spec.singular.has(field)) {
          // A duplicate of a singular message-typed field merges in
          // canonical parsers and replaces here; reject.
          if (seenSingular.has(field)) throw new Error("Invalid event");
          seenSingular.add(field);
        }
        if (spec.arms?.has(field)) {
          if (seenArm !== 0 && seenArm !== field) throw new Error("Invalid event");
          seenArm = field;
        }
        const child = spec.descend[field];
        if (child !== undefined) {
          const childSpec = SCAN_SPECS[child];
          if (childSpec !== undefined) {
            scanMessage(data.subarray(cursor.offset, cursor.offset + length), childSpec);
          }
        }
      }
      cursor.offset += length;
    } else if (wireType === 5) {
      cursor.offset += 4;
    } else {
      throw new Error("Invalid event");
    }
    if (cursor.offset > data.length) throw new Error("Invalid event");
  }
  if (groupDepth !== 0) throw new Error("Invalid event");
}

/**
 * Rejects a wire envelope that repeats a KNOWN event tag, then walks each
 * event payload through the scan graph. Canonical protobuf merges repeated
 * message occurrences where ts-proto overwrites, so two runtimes would
 * surface different events; neither silent behaviour is acceptable. Unknown
 * field numbers are protobuf's to ignore — repeated or not — so forward
 * compatibility is untouched.
 */
function assertNoRepeatedTopLevelTags(data: Uint8Array): void {
  const seen = new Set<number>();
  const cursor = { offset: 0 };
  // Legacy group wire types nest; everything inside a group is an unknown
  // field a protobuf decoder skips, so the scan skips it too.
  let groupDepth = 0;
  while (cursor.offset < data.length) {
    const tag = readVarint(data, cursor);
    const field = Math.floor(tag / 8);
    const wireType = tag % 8;
    // Field zero is not a legal tag: canonical decoders reject it while
    // ts-proto silently stops reading, which would truncate the stream in
    // one runtime and error in another.
    if (field === 0) {
      throw new Error("Invalid event");
    }
    if (wireType === 3) {
      groupDepth += 1;
      continue;
    }
    if (wireType === 4) {
      groupDepth -= 1;
      if (groupDepth < 0) throw new Error("Invalid event");
      continue;
    }
    if (groupDepth === 0 && ENVELOPE_TAGS.has(field)) {
      if (seen.has(field)) {
        throw new Error("Invalid event");
      }
      seen.add(field);
    }
    if (wireType === 0) {
      readVarint(data, cursor);
    } else if (wireType === 1) {
      cursor.offset += 8;
    } else if (wireType === 2) {
      const length = readVarint(data, cursor);
      if (cursor.offset + length > data.length) throw new Error("Invalid event");
      if (groupDepth === 0) {
        const child = ENVELOPE_SCAN[field];
        if (child !== undefined) {
          const childSpec = SCAN_SPECS[child];
          if (childSpec !== undefined) {
            scanMessage(data.subarray(cursor.offset, cursor.offset + length), childSpec);
          }
        }
      }
      cursor.offset += length;
    } else if (wireType === 5) {
      cursor.offset += 4;
    } else {
      throw new Error("Invalid event");
    }
    if (cursor.offset > data.length) throw new Error("Invalid event");
  }
  if (groupDepth !== 0) throw new Error("Invalid event");
}

export function decode(data: Uint8Array): BaseEvent {
  assertNoRepeatedTopLevelTags(data);
  const envelope = protoEvents.Event.decode(data);
  // Exactly one oneof entry. ts-proto's field-per-entry decoding cannot
  // reproduce protobuf's last-field-wins for a malformed envelope carrying
  // several, so the deterministic behaviour is to reject it loudly rather
  // than silently pick a different event than another runtime would.
  const populated = Object.entries(envelope).filter(([, value]) => value !== undefined);
  if (populated.length !== 1) {
    throw new Error("Invalid event");
  }
  const entry = populated[0];
  // The oneof entry selected the message shape, so it names the type; a
  // base_event.type that disagrees is a malformed event, not a tiebreak.
  const entryType = ENVELOPE_TYPE[entry[0]];
  if (entryType === undefined) {
    throw new Error("Invalid event");
  }
  const decoded = entry[1] as LooseRecord;
  const base = asRecord(decoded.baseEvent);
  if (!base) {
    throw new Error("Invalid event");
  }
  const declaredType = protoEvents.EventType[base.type as number];
  if (declaredType !== entryType) {
    throw new Error(
      "Invalid event: envelope carries " +
        entryType +
        " but the base event declares " +
        String(declaredType),
    );
  }
  decoded.type = entryType;
  decoded.timestamp = base.timestamp;
  decoded.rawEvent = base.rawEvent;
  // Struct decodes an absent object to undefined, so an event that carried no
  // metadata stays without the key rather than gaining an empty one.
  if (base.metadata !== undefined) {
    decoded.metadata = base.metadata;
  }
  delete decoded.baseEvent;

  if (decoded.type === "MESSAGES_SNAPSHOT" && Array.isArray(decoded.messages)) {
    decoded.messages = (decoded.messages as unknown[]).map(fromWireMessage);
  }
  if (decoded.type === "RUN_FINISHED") {
    const record = decoded as LooseRecord;
    const wireOutcome =
      typeof record.outcome === "string" && record.outcome !== ""
        ? (record.outcome as string)
        : undefined;
    // An unknown discriminator must not silently decode to "no outcome",
    // which would imply success; the JSON path errors on it, so this does too.
    if (wireOutcome !== undefined && !["success", "interrupt"].includes(wireOutcome)) {
      throw new Error("Invalid event: unknown outcome " + wireOutcome);
    }
    const payload: LooseRecord = {};
    payload.interrupts = record.interrupts;
    delete record.interrupts;
    delete record.outcome;
    if (wireOutcome === undefined) {
      if (asArray(payload.interrupts).length > 0) {
        throw new Error("Invalid event: absent outcome cannot carry interrupts");
      }
    }
    if (wireOutcome === "success") {
      if (asArray(payload.interrupts).length > 0) {
        throw new Error("Invalid event: outcome success cannot carry interrupts");
      }
      record.outcome = { type: "success" };
    }
    if (wireOutcome === "interrupt") {
      record.outcome = { type: "interrupt", interrupts: asArray(payload.interrupts) };
    }
  }
  if (decoded.type === "SUBAGENT_FINISHED") {
    const record = decoded as LooseRecord;
    const wireOutcome =
      typeof record.outcome === "string" && record.outcome !== ""
        ? (record.outcome as string)
        : undefined;
    // An unknown discriminator must not silently decode to "no outcome",
    // which would imply success; the JSON path errors on it, so this does too.
    if (wireOutcome !== undefined && !["success", "suspended"].includes(wireOutcome)) {
      throw new Error("Invalid event: unknown outcome " + wireOutcome);
    }
    const payload: LooseRecord = {};
    payload.interruptIds = record.interruptIds;
    delete record.interruptIds;
    delete record.outcome;
    if (wireOutcome === undefined) {
      if (asArray(payload.interruptIds).length > 0) {
        throw new Error("Invalid event: absent outcome cannot carry interruptIds");
      }
    }
    if (wireOutcome === "success") {
      if (asArray(payload.interruptIds).length > 0) {
        throw new Error("Invalid event: outcome success cannot carry interruptIds");
      }
      record.outcome = { type: "success" };
    }
    if (wireOutcome === "suspended") {
      record.outcome = {
        type: "suspended",
        ...(asArray(payload.interruptIds).length > 0 ? { interruptIds: payload.interruptIds } : {}),
      };
    }
  }
  if (decoded.type === "STATE_DELTA" && Array.isArray(decoded.delta)) {
    for (const operation of decoded.delta as LooseRecord[]) {
      const opName =
        protoPatch.JsonPatchOperationType[operation.op as protoPatch.JsonPatchOperationType];
      // A wire value outside the enum must not invent an operation.
      if (typeof opName !== "string" || opName === "UNRECOGNIZED") {
        throw new Error("Invalid event: unknown patch operation");
      }
      operation.op = opName.toLowerCase();
      Object.keys(operation).forEach((key) => {
        if (operation[key] === undefined) {
          delete operation[key];
        }
      });
    }
  }
  if (decoded.type === "ACTIVITY_DELTA" && Array.isArray(decoded.patch)) {
    for (const operation of decoded.patch as LooseRecord[]) {
      const opName =
        protoPatch.JsonPatchOperationType[operation.op as protoPatch.JsonPatchOperationType];
      // A wire value outside the enum must not invent an operation.
      if (typeof opName !== "string" || opName === "UNRECOGNIZED") {
        throw new Error("Invalid event: unknown patch operation");
      }
      operation.op = opName.toLowerCase();
      Object.keys(operation).forEach((key) => {
        if (operation[key] === undefined) {
          delete operation[key];
        }
      });
    }
  }
  if (decoded.type === "RUN_FINISHED") {
    if (Array.isArray(decoded.usage) && decoded.usage.length === 0) {
      delete decoded.usage;
    }
  }
  if (decoded.type === "RUN_ERROR") {
    if (Array.isArray(decoded.usage) && decoded.usage.length === 0) {
      delete decoded.usage;
    }
  }
  if (decoded.type === "RUN_STARTED" && decoded.input !== undefined) {
    decoded.input = fromWireRunAgentInput(decoded.input);
  }

  dropUndefinedDeep(decoded);

  // Same gate as encode: validate what the SDK knows, carry the rest.
  if (KNOWN_TO_CORE.has(decoded.type as string)) {
    return EventSchemas.parse(decoded) as BaseEvent;
  }
  return decoded as unknown as BaseEvent;
}
